lazy weather app (Olof)
Technigo/project-weather-app pull request #100
Opened 2020-09-25 17:22 UTC by luuf81

Link to my deployed project:https://lazy-weather-app.netlify.app/

My reflections on how this week's project turned out: 

Turned out great. Was great fun!

Things I'd like to have clarified or explained in more detail:

- Still a bit unclear about the details for how fetch works. Would like to understand more how to use callback functions with fetch, but I think this will also get clearer with time.
- My main problem at the moment is CSS. Feels like I´m writing way more CSS than I should, but was needed for things to work the way I want. Going forward I would like to have a better plan/understanding on how to efficiently implement CSS without all the finetuning at the end.

2020-09-30 20:58 UTC, Bluepoisson approved these changes
Well done Olof! A minimalistic, sleek weather app for anybody, anywhere to use at any time. Weather and wind direction icons enhance and make the experience easy. The padding and margins along with mobile display make it easy on the eye. Great features and methods. Keep going!

2020-09-30 20:58 UTC, Bluepoisson commented on code/weather.js
> +    fetch(`https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&appid=7d01b328e34c450986cb7faef032a771`)
Would have loved to see an appid variable here too, after the ${lat} and ${lon} an ${apiKey} to keep it tight :)

2020-09-30 20:58 UTC, Bluepoisson commented on code/weather.js
> +  const slicedForecast = forecast.daily.slice(0, 5);
Great with slice method over splice and split. Creating a new one leaving the original array intact and not having to convert it into a string

2020-09-30 20:58 UTC, Bluepoisson commented on code/weather.js
> +const getLocation = () => {
Yes!

2020-09-30 20:58 UTC, Bluepoisson commented on code/weather.js
> +    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city},Sweden&units=metric&APPID=7d01b328e34c450986cb7faef032a771`)
${appId}

2020-09-30 20:58 UTC, Bluepoisson commented on code/style.css
> +    display: none;
Thoughtful choice to have display none on the wind-dir, could have been difficult to read and made the design heavy on a mobile phone.

2020-10-13 09:43 UTC, EmOlsz requested changes
Hey Olof! Once again, I'm impressed by your code. You've done a lot of extra requirements and you did them well :) Your app is clean and well designed.
You didn't avoid some mistakes, I have pointed them out in comments with info `needs to be fixed`. Please, take a look on them, hope they will help you for the future.
After changes are provided, I will approve your project

2020-10-13 09:43 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="style.css" />
`./` - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/index.html
> +                    style="font-size:35px; margin-right:10px;">&#xe55c;</i></button>
wrong line breaks - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/style.css
> +    font-family: "Roboto";
Font fallback would be nice here :)

2020-10-13 09:43 UTC, EmOlsz commented on code/style.css
> +    background: url("./search_icon.png") no-repeat 90% 50%;
good job with this shorthand!

2020-10-13 09:43 UTC, EmOlsz commented on code/style.css
> +    margin: 0px;
`margin: 0;`  - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/style.css
> +    margin: 10px 0 10px 0;
`margin: 10px 0;` is shorthand for that - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/style.css
> +    width: 10px !important;
Do you know why you had to use `!important`? It's because you used reference by selector in other place in your CSS file, precisely I'm talking about 

```
.day-temp span {
    width: 65px;
    text-align: right;
}
```

from line 111. If you would style elements by classes only, this problem would not occur.
I'm trying to show you over here that this problems will occur a lot. Your application right now is relatively small and it's easy to detect mistake, but believe me that in projects which are being developed by years it would be impossible (or would cost a loooot of time to refactor). As I remember your code reviews from previous weeks, this is the first situation it which you can see disadvantages of mixing CSS reference. Please, consider this is as important reminder :)
Needs to be fixed of course

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +window.onload = () =>  getLocation();
Great job :)

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +  if (navigator.geolocation) {
I'm happy to see coercion check!

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +    getLatLong(city)
So, do we use semicolons or not? - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +const getCity = (position) => {
`const getCity = position => { ... }` (no need for parentheses around single argument) - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +        .then(forecast => {
wrong indentation - needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +    });
You haven't implemented `.catch()` after second `.then()`. Because of that you didn't detected issue with Vindo city - your weather app return 404 error for that city. We will not fix this issue on API side (it's theirs error), but we can at least inform user about it. How?

```
fetch(`...`)
    .then(response => response.json())
    .then(forecast => ...)
    .catch(err => console.error(err))
```

Notice that I used new, special type of console - `console.error()`. It's normal `console.log()` with one addition - message displayed in Console tab will have red background indicating that something probably went wrong.

Needs to be fixed

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +      : [
Very nice and clean code - I like to do it this way as well!

2020-10-13 09:43 UTC, EmOlsz commented on code/weather.js
> +  const generateForecast = (forecast) => {
Wrong indentation in whole file - needs to be fixed

2020-10-15 13:53 UTC, luuf81 commented on code/weather.js
> +    });
@EmOlsz When I try to implement your .catch... syntax it throws errors -  "declaration or statement expected", "try expected". It does the same even if I try other examples. Is there something I´m missing?

2020-10-15 13:53 UTC, luuf81 commented on code/weather.js
> +      : [
Thanks :)

2020-10-15 14:25 UTC, luuf81 commented on code/weather.js
> +    });
Okay code works now when I move catch to after tthe first .then ("response")

2020-10-15 14:58 UTC, luuf81 commented on code/style.css
> +    width: 10px !important;
Thanks for pointing this out - I did read somewhere it was not recommended to use !important, but decided in. the end since it worked :). Have now changed styling to classes and removed !important since its no longer important :)

2020-10-15 15:06 UTC, EmOlsz approved these changes

2020-10-15 15:06 UTC, luuf81 commented
@EmOlsz @Bluepoisson Thank you for the thorough code review. I will now hopefully get rid of some bad coding habits as pointed out by the both of you. I have made fixes according to the change requests.

2020-10-15 15:07 UTC, EmOlsz commented
> @EmOlsz @Bluepoisson Thank you for the thorough code review. I will now hopefully get rid of some bad coding habits as pointed out by the both of you. I have made fixes according to the change requests.

Thank you Olof, project is officially approved!

2021-02-16 17:53 UTC, closed without merging