Week 5 - Karin Nordkvist (Weatherbug)
Technigo/project-weather-app pull request #103
Opened 2020-09-26 09:00 UTC by karinnordkvist

Link to my deployed project: https://weatherbug.netlify.app/

My reflections on how this week's project turned out:
I really enjoyed this week's task. It was very challenging at times, and also very rewarding as I learned to manage and modify my functions.  

Things I'd like to have clarified or explained in more detail:
The text-field and the button is not part of a form, due mainly to time limitation. I will work on this whenever I get the chance.

2020-09-29 17:45 UTC, AnnaHellqvist approved these changes
Great job on the weather project Karin! I really enjoyed the humor you brought to the page with the giphs! Your page works fine and is responsive. Your code is clean and the comments makes it easy to follow and understand 🥇 You really manage to include a lot from the project requirements/goals, if not all :) Be proud of yourself and keep up the good work!

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/index.html
> +    <!-- LOCATION SEARCH -->
Overall good commenting, indentation and naming of classes :) 🥇

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/style.css
> +#day1, #day2, #day3, #day4, #day5 {
Is it possible to use the day--temp class for this styling?

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/script.js
> +// HTML QUERIES
Great job with variables for queries, makes the code cleaner further down! 👍 💯

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/script.js
> +const weatherDescriptions = [
nice approach with array of objects, I tried this myself but couldnt get it to work as I wanted it to :) 👍

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/script.js
> +// to use the function for different types of API-requests
Good commenting! Makes it easy for me to understand!

2020-09-29 17:45 UTC, AnnaHellqvist commented on code/script.js
> +      temperatureTag.innerHTML = roundedNumber(weather.main.temp) + ` C°`;
Nice that you use a lot of functions 👍

2020-10-12 16:11 UTC, HIPPIEKICK commented on code/api.js
> +export const API_KEY = 'ff72c94f2c17b0a54c4cd7444d1d002b';
Ohh ;)

2020-10-12 16:16 UTC, HIPPIEKICK commented on code/script.js
> +    });
😆 ⭐

2020-10-12 16:18 UTC, HIPPIEKICK commented on code/script.js
> +  if (e.key === 'Enter') {
⭐

2020-10-12 16:19 UTC, HIPPIEKICK commented on code/script.js
> +function geoLocate() {
Arrow function? 😇

2020-10-12 16:20 UTC, HIPPIEKICK commented on code/script.js
> +  const dt = new Date(t * 1000);
Hmm, can we have more descriptive names than `t` and `dt`?

2020-10-12 16:22 UTC, HIPPIEKICK commented on code/script.js
> +};
Can you think of a way to make this shorter using the index?

2020-10-12 16:22 UTC, HIPPIEKICK commented on code/style.css
> +
Unnecessary whitespace

2020-10-12 16:22 UTC, HIPPIEKICK commented on code/style.css
> +}
🤩

2020-10-12 16:25 UTC, HIPPIEKICK requested changes
Good job Karin! Be consistent with arrow functions and try to keep the styling to the CSS-file (by toggling/adding/removing classes). Some more comments for the complex parts of your code would be nice as well :)

Since one of the requirements this week was that the app should be responsive - take another look at the image as it causes some horizontal scrolling on your page. Get rid of that side scroll and you'll be approved!

2020-10-12 16:32 UTC, karinnordkvist commented
> Good job Karin! Be consistent with arrow functions and try to keep the styling to the CSS-file (by toggling/adding/removing classes). Some more comments for the complex parts of your code would be nice as well :)
> 
> Since one of the requirements this week was that the app should be responsive - take another look at the image as it causes some horizontal scrolling on your page. Get rid of that side scroll and you'll be approved!

@HIPPIEKICK Thank you for the great feedback. Big OOPS on the function not being written correctly, sorry about that. Will definitely go back into my code and look at these things. However, I can't seem to get the horizontal scrolling to happen for me, could you send a screenshot and/or let me know what screensize you experienced this? 🤩🤓🤓

2020-10-13 07:40 UTC, HIPPIEKICK commented
> > Good job Karin! Be consistent with arrow functions and try to keep the styling to the CSS-file (by toggling/adding/removing classes). Some more comments for the complex parts of your code would be nice as well :)
> > Since one of the requirements this week was that the app should be responsive - take another look at the image as it causes some horizontal scrolling on your page. Get rid of that side scroll and you'll be approved!
> 
> @HIPPIEKICK Thank you for the great feedback. Big OOPS on the function not being written correctly, sorry about that. Will definitely go back into my code and look at these things. However, I can't seem to get the horizontal scrolling to happen for me, could you send a screenshot and/or let me know what screensize you experienced this? 🤩🤓🤓

Of course! Between 950px - 1200px the image seems to be too wide to fit to the side of the weather data :)
<img width="763" alt="Skärmavbild 2020-10-13 kl  09 39 22" src="https://user-images.githubusercontent.com/51529201/95830449-fb92db00-0d37-11eb-9e8f-d0547f4efa13.png">

2020-10-21 15:24 UTC, HIPPIEKICK approved these changes

2021-02-16 17:53 UTC, closed without merging