Weather App - Project 6
Technigo/project-weather-app pull request #106
Opened 2020-09-26 14:49 UTC by Andrea-Osmar

Link to my deployed project: https://unicornweather.netlify.app/

My reflections on how this week's project turned out: it turned out alright.. I am very proud that i actually managed to get this project done. However I know that the sunrise & sunset time is swedish time nomather what city you choose. There is also something a little off with the weather container on my phone but not in the dev tools :/ will try to figure that out
I know that i have not commited very much but I had some issues with my internet and GIthub..

Things I'd like to have clarified or explained in more detail: help with sunrise & sunset time. I am still very unsure on how fetch and promises work..

2020-09-30 15:37 UTC, karolinalbinsson requested changes
Hey Andrea!
Great job with the weather app! 

Some reflections:
I love your design and think the app is very pleasing to look at. The different images in the background depending of the weather gives your application a really nice touch. Also your choice of font and margins/padding makes it pleasant for the eye. 

When I read your own reflections of how you think the project turned out, I sense some disappointment in the text(?), but I really don't think you should be disappointed at all! You have done a great job with letting the user select a city, changing the appearance of the app depending of weather, and made it responsive as well. 

I struggled with getting the time in the correct format aswell, it has to do with the date objects and functions that are converting the time to whichever timezone is on the client system (I hope that whomever of the code coaches are doing this review can explain it a bit more.)

I have some remarks and I believe you need to make some small changes for fulfilling the general requirements of how to write our code.You can see my remarks in the comments on the files, but here are the ones that need action:

1. You do use a lot of styling by ID, and I think you should consider changing it to style by class name.
2. Also have a look at the section named Template literals here and use that approach: (https://www.notion.so/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e)
 
Overall - good job!! :+1: :1st_place_medal:

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +    filteredForecastNoon.forEach((forecast) => {
I think you could work with your indentation in some of your functions, like this one. It is a bit of a struggle to read it.

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +    let searchTerm = document.getElementById("searchInput").value;
Consider changing this to a const since the value of searchTerm is never changed in your function

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +    // REMOVE FORECAST WHEN CHANGING CITY
Good that you have put a comment here, so I understand what's going on :)

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +    const CityHeader = document.getElementById("cityHeader");
camelCase, I think you just forgot it here. :)

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +const readForecast = (json) => {
This function is really big, could it be divided into multiple functions that would be called by this one?

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +    }
I didn't receive any feedback from the app when I searched for a city that doesn't exist, maybe an else statement could fix that?

2020-09-30 15:37 UTC, karolinalbinsson commented on style.css
> +#documentIconImg:hover {
This animation is really cute! :+1:

2020-09-30 15:37 UTC, karolinalbinsson commented on script.js
> +        "Winds at " + Math.floor(resultFromServer.wind.speed) + " m/s";
I suggest using string templating instead of + here:
`Winds at ${variable} m/s`

2020-10-13 09:38 UTC, HIPPIEKICK commented on script.js
> +    const forecastContainer2 = document.getElementById("forecast2");
What's the difference between these two? Could we create more descriptive variable names to make the difference clear?

2020-10-13 09:43 UTC, HIPPIEKICK commented on style.css
> +    position: absolute;
Why `position: absolute;` here without positioning? It makes the container go to the far left side
<img width="934" alt="Skärmavbild 2020-10-13 kl  11 42 57" src="https://user-images.githubusercontent.com/51529201/95844467-3ea97a00-0d49-11eb-9a02-936801c20956.png">

2020-10-13 09:50 UTC, HIPPIEKICK requested changes
Good job Andrea, especially nice with the search function! Take a look at Karolin's comments and also the comment I made about `position: absolute;`.

Regarding the formatting of the dates, take a look at this [Slack-thread](https://technigo.slack.com/archives/C6QAN25EV/p1601018607030900) and this [Stack Overflow-question](https://stackoverflow.com/c/technigo/questions/1586).

2020-10-18 10:31 UTC, Andrea-Osmar commented on style.css
> +    position: absolute;
A question, on my computer the container never goes to the far left.
I positioned the element in my javascript, and I needed position absolute for that to work. 
Do I then also need to position the element in css?


  // POSITION VISIBLE & IN MIDDLE OF SCREEN
    weatherContainer.style.left = `calc(50% - ${weatherContainerWidth / 2}px)`;
    weatherContainer.style.top = `calc(50% - ${weatherContainerHeight / 1.5}px)`;
    weatherContainer.style.visibility = "visible";

2020-10-21 15:27 UTC, HIPPIEKICK commented on style.css
> +    position: absolute;
That's really weird! I can't seem to recreate the issue now either. Sorry about that, approving!

2020-11-26 16:14 UTC, HIPPIEKICK approved these changes

2021-02-16 17:53 UTC, closed without merging