Project 6 - Sara Heijkenskjöld
Technigo/project-weather-app pull request #107
Opened 2020-09-26 15:35 UTC by sarahejhej

Link to my deployed project:
https://distracted-visvesvaraya-168733.netlify.app/

My reflections on how this week's project turned out:
I'm very happy with the end product, except for the search, and search button, and some parts of the design. I tried out a different approach in my JavaScript code, and favoured legibility before brevity. I would have liked to used CSS grid in addition to all my flexboxes.

Things I'd like to have clarified or explained in more detail:
I'm still stuck with the strange auto formatting in the JavaScript file. I would appreciate feedback on how to improve both the search bar and my code in general.

2020-09-28 17:49 UTC, thereselinden approved these changes
Overall, great job, I can see that you put a lot of work here. 
I really like your design and the extra info you added depending on device!

You could work in consistency in line-breaks and indentations and some structuring of code.
Your page takes a while to load, perhaps this could be done by structuring the javascript in a different way? Or minimize the background image?

Very impressed of your js skill!!!! 🥇

2020-09-28 17:49 UTC, thereselinden commented on code/script.js
> +
Very impressed of your js skills. Had a hard time to follow along with your code, partly because I don't really understand how all functions are connected together. Maybe structuring your code a bit different could make it a bit easier to follow the code.

2020-09-28 17:49 UTC, thereselinden commented on code/script.js
> +  fetch(url)
If I don't select any city, I receive error messages in the console, the error messages starts here on line 77.

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +  margin: 25px 0;
You can remove justify-content, align-items (times two) the value that separates the p elements is the margin.

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +  width: 100%;
I don't think you need to specify: 
- flex values or width and height.

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +  animation-direction: alternate;
The animation alternate does not seem to work, the animation stops after a while.

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +    rgba(255, 255, 255, 1)
Nice that are using linear-gradient!!! 👍

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +}
For readability I think this code should be moved up, accordingly to your html structure.

2020-09-28 17:49 UTC, thereselinden commented on code/style.css
> +  margin-left: 2%;
I see that you sometimes use px and sometimes use %, might be good to be consistent.

2020-09-28 20:16 UTC, sarahejhej commented on code/script.js
> +  function gotLocation(position) {
Yes, since these anonymous 'functions' are passed as arguments to other methods I hade to declare them as 'functions'.

2020-09-28 20:18 UTC, sarahejhej commented on code/script.js
> +    API_URL_TODAY = `https://api.openweathermap.org/data/2.5/weather?q=${cityName}&units=metric&APPID=${API_KEY}`;
I tried to remove them because it didn't make sense to reassign them, but that didn't work out so I just left them there  😅

2020-09-28 20:21 UTC, sarahejhej commented on code/script.js
> +const fetchWeatherForecast = (url) => {
Yes I tried this method on purpose and I actually felt that it was easier to get a good overview of the code. I get more confused by many smaller functions. But good to know that it affected readability!

2020-09-28 20:23 UTC, sarahejhej commented on code/script.js
> +  fetch(url)
I decided to just console.log the error messages. I'm a bit scared/confused by error handling

2020-10-01 10:31 UTC, sarahejhej commented on code/index.html
> +          <input id="input" type="text" placeholder="" />
Yes, I'm not very happy with my search bar. Thanks for the suggestion!

2020-10-01 10:37 UTC, sarahejhej commented
Thanks for the comments! I really want to make the code structured and readable, so I really appreciate it! 
The strange line breaks are not intentional, my vs code does some auto formatting that I can't work out how to change. Will look into indentation and consistency 👍

2020-10-13 12:27 UTC, EmOlsz requested changes
Great job Sara! Same as before, I'm impressed. Both geolocation method and visual aspects of your app looks very professional :)
There are some minor things I would like you to fix - please, take a look on my comments and provide changes

2020-10-13 12:27 UTC, EmOlsz commented on code/script.js
> +};
Indeed!

2020-10-13 12:27 UTC, EmOlsz commented on code/script.js
> +        return temp;
`return numberOneDecimal(temperature.main.temp);` would be enough. No need to create variable if only thing you do with it is returning it

2020-10-13 12:27 UTC, EmOlsz commented on code/script.js
> +  return Math.round(number * 10) / 10;
More semantic name for that function would be `convertNumberToOneDecimal`

2020-10-13 12:27 UTC, EmOlsz commented on code/script.js
> +const numberNoDecimal = (number) => {
`convertNumberToNoDecimal`

2020-10-13 12:27 UTC, EmOlsz commented on code/style.css
> +  width: 100%;
Yep, width and height are in this case irrelevant.
Width - because all block elements (so, the one with `display: block`) have width set to 100% by default
Height - because this exact element, since it's wrapper of everything else, by definition has 100% of height

2020-10-13 12:27 UTC, EmOlsz commented on code/style.css
> +  margin-left: 2%;
In general I agree, but if there is proper reason to use both `px` and `%`, we should use them

2020-11-04 20:44 UTC, sarahejhej commented on code/index.html
> +                <img class="hour-icon icon" src="" alt="weather icon" />
The path to the src is set in the script.js (line 156-157), so I think I must declare it as an empty string here

2020-11-05 15:30 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging