Weather App - Ylva Nilsson
Technigo/project-weather-app pull request #108
Opened 2020-09-26 17:26 UTC by ylvan75

**Link to my deployed project:**
[https://weather-app-by-ylva.netlify.app/](https://weather-app-by-ylva.netlify.app/)

**My reflections on how this week's project turned out:**
I'm proud of how we've worked together this week. Felt nice that we had most of the Javascript
part in place and basic design early in the week.

I think the structure of the JS-file feels good and I hope the code is easy to read.

**Things I'd like to have clarified or explained in more detail:**
I would have liked to create a function that takes search city and return with timezone that city shall have
and use the timezone value in the `Date()` object.

2020-09-28 17:54 UTC, trangtara reviewed
Hi Ylva, I had a nice experience while reviewing your code and did learn a lot from you. Simple and clean codes on all HTML, css and JS.

2020-09-28 17:54 UTC, trangtara commented on code/index.html
> +                document.getElementById('btnSearch').click()"
This is new to me. So great!!!!

2020-09-28 17:54 UTC, trangtara commented on code/index.html
> +    <script src="weather.js"></script>
Super clean HTML file. Well done!

2020-09-28 17:54 UTC, trangtara commented on code/style.css
> +}
Super! Simple and efficient code to capitalize the first letter of the description.

2020-09-28 17:54 UTC, trangtara commented on code/style.css
> +  text-align: end;
cool with text-align: end.

2020-09-28 17:54 UTC, trangtara commented on code/style.css
> +}
css codes are clean and consistent. Love it!!!

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +
I like the way to set the default page.

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +  weatherTodayHTML += `<p class="temp-today"> ${temperature}\xB0 </p>`;
Wow, I learned one new thing here about xB0.

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +};
Simple and effective. Nice job!

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +    });
Very clean code.

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +    hour: "2-digit",
I like the way you separate functions into different sections, which makes your code very easy to follow. The note/comments are very helpful to read the code too.

2020-09-28 17:54 UTC, trangtara commented on code/weather.js
> +};
Nice design! changing background according to the temperature.

2020-09-28 18:03 UTC, trangtara approved these changes
I just add a suggestion to the search function. It's not the requirement of the project, just a nice thing to do.

2020-09-28 18:03 UTC, trangtara commented on code/weather.js
> +};
Maybe a message/alert in case that users type in a city that does not exist will be helpful here.

2020-10-13 13:36 UTC, EmOlsz requested changes
Good job Ylva! I like how consistent your code and flow of it is. Your strategy for executing functions is well done :)
There are some minor changes I would like to see, take a look on my comments and provide them. After that, I'll approve your project

2020-10-13 13:36 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="style.css" />
`href="./style.css"`

2020-10-13 13:36 UTC, EmOlsz commented on code/index.html
> +            >Look up the weather for favourite city</label
Wrong line breaks

2020-10-13 13:36 UTC, EmOlsz commented on code/index.html
> +            onclick="citySelected();"
No need for semicolon here

2020-10-13 13:36 UTC, EmOlsz commented on code/index.html
> +    <script src="weather.js"></script>
`src="./weather.js"`

2020-10-13 13:36 UTC, EmOlsz commented on code/style.css
> +  margin: 0px 10px;
We don't have to write `px` if value is 0, `margin: 0 10px;` is completely fine :)

2020-10-15 16:13 UTC, ylvan75 commented on code/index.html
> +    <link rel="stylesheet" href="style.css" />
Fixed!

2020-10-15 16:14 UTC, ylvan75 commented on code/index.html
> +    <link rel="stylesheet" href="style.css" />
Fixed!

2020-10-15 16:15 UTC, ylvan75 commented on code/index.html
> +    <script src="weather.js"></script>
Fixed!

2020-10-15 16:16 UTC, ylvan75 commented on code/style.css
> +  margin: 0px 10px;
Fixed!

2020-10-15 16:17 UTC, ylvan75 commented on code/style.css
> +  top: 0px;
Fixed!

2020-10-15 16:17 UTC, ylvan75 commented on code/weather.js
> +  return roundedTemp;
Fixed!

2020-10-15 16:50 UTC, ylvan75 commented on code/index.html
> +                document.getElementById('btnSearch').click()"
@EmOlsz I have now placed this part in the .js. Perhaps I could have done the code nicer. What does it mean when I write input.addEventListner(... )  ?

2020-10-17 09:35 UTC, EmOlsz commented on code/index.html
> +                document.getElementById('btnSearch').click()"
This method attaches new "action to be done" to specific event (click, key push, focus, mouse move etc.). It's just an alternative to writing `onclick`, `onmousemove` etc. directly in HTML

2020-10-17 09:36 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging