Project Weather App - Johanna Rexin
Technigo/project-weather-app pull request #111
Opened 2020-09-26 22:44 UTC by johannarexin

2020-09-30 15:17 UTC, moablomkvist requested changes

2020-09-30 15:17 UTC, moablomkvist commented on code/script.js
> +    // const sunsetValue = weatherObject.sys.sunset;
Maybe you can try to make a function of it instead.
I made a function of sunrise and a function of sunset. Like this:  
```suggestion
  const weatherSunrise = () => {
  const dateSunrise = new Date(json.sys.sunrise * 1000);
  const timeSunrise = dateSunrise.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
  });
  document.getElementById('sunrise').innerHTML = timeSunrise;
};
weatherSunrise();
```

2020-09-30 15:17 UTC, moablomkvist commented on code/script.js
> +// .then((forecast) => {
We got this code in the brief: 
const filteredWeek = json.list.filter(item => item.dt_txt.includes('12:00'));

Use it for create the filtered list from the API and then use forEach to modify temperature and weekdays. :)

2020-09-30 15:17 UTC, moablomkvist commented on code/script.js
> +// })
You can do this!! 💪

2020-09-30 15:17 UTC, moablomkvist commented on code/style.css
> +@media (min-width: 668px) and (max-width: 1024px) {
Good! Responsive <3

2020-09-30 15:17 UTC, moablomkvist commented on code/style.css
> +    background-image: url("images/background_image.jpg");
Really like your background-image!

2020-10-13 14:18 UTC, HIPPIEKICK commented on code/index.html
> +            <h1>Today's weather in:</h1>
That's a really good metaphor!

2020-10-13 14:22 UTC, HIPPIEKICK commented on code/script.js
> +    // const sunsetValue = weatherObject.sys.sunset;
If you search on sunset in Stack Overflow there are some questions about this as well, if you want to read more :)

2020-10-13 14:24 UTC, HIPPIEKICK commented on code/script.js
> +const apiFiveDaysForecast = 'https://api.openweathermap.org/data/2.5/forecast?q=Stockholm,Sweden&units=metric&APPID=380f07f94efb48727a6ae5c8f7d15f5d';
You have the API-key as a variable, so you can use it inside your other strings using template literals:
`https://api.openweathermap.org/data/2.5/weather?q=Stockholm,Sweden&units=metric&APPID=${apiKey}`

2020-10-13 14:32 UTC, HIPPIEKICK commented on code/script.js
> +// .then((forecast) => {
A good idea is to begin with logging the data to see how it comes back from the API. Start with `console.log(forecast)` to see how this JSON response is different from the first fetch you did. As Moa mentioned all the forecast data is in an array called `list` this time.

2020-11-21 22:11 UTC, johannarexin commented
Hello, now I have updated my code and pushed a new version :) 
Best and good night, Johanna

2020-11-24 18:07 UTC, HIPPIEKICK commented
> Hello, now I have updated my code and pushed a new version :)
> Best and good night, Johanna

Looks really good Johanna, great job 💪 🥳

2020-11-24 18:08 UTC, HIPPIEKICK approved these changes

2021-02-16 17:53 UTC, closed without merging