Weather App - Therese Lindén
Technigo/project-weather-app pull request #113
Opened 2020-09-27 06:14 UTC by thereselinden

**Link to my deployed project:**
https://sleepy-yalow-76fedf.netlify.app/

**My reflections on how this week's project turned out:**
I am really proud of this week that I managed to fulfill red level. I'm glad that we started this week with some mob-programming within our Zebra-team. It was great that we could learn so much from each other. 

**Things I'd like to have clarified or explained in more detail:**
How to handle API error, how to write functions to capture local time (when using open search).

2020-09-28 12:37 UTC, idsintehittapa approved these changes
Hey Therese!
Great job with the weather-app :) First of all, your design is really amazing! The features that you added with local time, uppercase function on the weather description and the search field are really cool!

You had a good use of functions and kept your fetch function relatively clean.

In general I think your code is well structured and you are using semantic HTML-tags and also naming the css-classes to names that make sense. Some suggestions would be to add some more comments in the CSS file (as you have in the JS file) for readability and clean your main folder (remove files that you don't use and add  a image folder to make a clearer structure)

See some other remarks in the comments, but over all - great job!!

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +    const weekday = printDay(filteredForcast.dt_txt);
In the API, use this "dt": 1601305200, instead of dt_txt because the format is not compatible with Safari, so when I look at your deployed site your forecast days says "Invalid Date" - I can give you a print screen if you want :)

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +//Fetch weather today API
Very nice usage of comments, it's easy to follow what you have been thinking

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +    weatherForcast += `<p>${dailyTemp} \xB0c/ ${humidity} %</p>`
Maybe add humidity inside as this ` humidity ${humidity} for end-user readability

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +    weatherForcast += `<p>${dailyTemp} \xB0c/ ${humidity} %</p>`
Nice with the \xB0c/

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +}
This is really neat!

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +}
That's a nice feature!

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +}
I don't really understand how it works but it's a really cool feature you put in.

2020-09-28 12:37 UTC, idsintehittapa commented on script.js
> +};
Maybe this could be moved to row 85 for logic reasons. Then all functions related to variables are all together

2020-10-01 12:36 UTC, thereselinden commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500&display=swap" rel="stylesheet">
Thank you for the input! =)

2020-10-01 12:41 UTC, thereselinden commented on index.html
> +    <section class="weather-container">
Thank you, I removed that class =)

2020-10-01 12:42 UTC, thereselinden commented on script.js
> +    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${citySearched}&units=metric&APPID=a0a9672a941bc58ae811a05987143dd5`)
I tried that, but could not make it work when I had an open search field. I will def give that a try in future projects.

2020-10-01 12:44 UTC, thereselinden commented on script.js
> +};
Thank you for the input, yes it would probably make the content load faster. I started to build the structure after Van's lecture and had no time to change it to be within the HTML.

2020-10-01 13:02 UTC, thereselinden commented on script.js
> +    const weekday = printDay(filteredForcast.dt_txt);
Great, thank you! I have changed that now! =)

2020-10-01 13:10 UTC, thereselinden commented on script.js
> +    weatherForcast += `<p>${dailyTemp} \xB0c/ ${humidity} %</p>`
Thanks for the input, was thinking about it but I didn't want to have to much text. I have changed it to wind speed now instead.

2020-10-01 13:11 UTC, thereselinden commented on script.js
> +};
Yes, thank you, I have moved it now!

2020-10-13 15:12 UTC, HIPPIEKICK commented
> **Link to my deployed project:**
> https://sleepy-yalow-76fedf.netlify.app/

Please add a working link!

2020-10-14 14:53 UTC, HIPPIEKICK commented on script.js
> +    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${citySearched}&units=metric&APPID=a0a9672a941bc58ae811a05987143dd5`)
The API-key could also be a variable :)

2020-10-14 14:56 UTC, HIPPIEKICK commented on script.js
> +}
⭐

2020-10-14 14:57 UTC, HIPPIEKICK commented on script.js
> +const iconMainDescription = item
Some missing semicolons in and after this function

2020-10-14 14:57 UTC, HIPPIEKICK commented on script.js
> +}
Here too --> `;`

2020-10-14 15:05 UTC, HIPPIEKICK requested changes
Wow, as Johanna said - nice design and cool search function. I would like to ask you to add some conditionals to display something when a city is not found. Right now it's just a lot of errors in the console. Also - be consistent with semicolons. I pointed it out in two places but I think there are some more missing :)

2020-10-15 07:01 UTC, thereselinden commented on script.js
> +    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${citySearched}&units=metric&APPID=a0a9672a941bc58ae811a05987143dd5`)
Thank you, will give that a try in other projects =)

2020-10-15 07:03 UTC, thereselinden commented on script.js
> +    return Math.round(number*10)/10;
I downloaded the prettier extension, and that made the trick. Thank you! =)

2020-10-15 07:07 UTC, thereselinden commented on script.js
> +const iconMainDescription = item
Thank you, removed the variable and used item instead.

2020-10-15 07:08 UTC, thereselinden commented on script.js
> +}
Thank you, I will always use prettier from now, it solved everything for mer =)

2020-10-15 10:09 UTC, thereselinden commented
Hi, 
I have added conditionals to the function citySelected and gave each fetch a catch element to log errors. The catch in the weather today fetch I return an alert message which will tell the user to do another search. I hope this is right way of doing it, otherwise please let me know if there is a better solution =)

2020-10-21 15:19 UTC, HIPPIEKICK commented
Looking great! 🤩
PS. Your indentation looks huge (it looks like there are tabs instead of spaces). Check your VSC Preferences, Settings, Tab Size (which should be 2).

2020-10-21 15:19 UTC, HIPPIEKICK approved these changes

2021-02-16 17:53 UTC, closed without merging