Wather App Moa
Technigo/project-weather-app pull request #115
Opened 2020-09-27 07:02 UTC by mhammarback

**Link to my deployed project:**
https://sunnydaysplease.netlify.app/

**My reflections on how this week's project turned out:**
I am quite happy with this weeks result. I did however after the demos on friday get new ideas and inputs in how to make my own project better. I decided not to do those changes - yet. But if change request is needed i will of course go back. I just did not have the time this weekend. If changes are made i would probably be able to make my code shorter and i understand that that is always good.  It was very fun working with the API, it feels "alive" so all in all a great week.

**Things I'd like to have clarified or explained in more detail:**
I think this week was pretty clear, it's more that i feel like there is so many ways to get the same result so sometimes it's hard to navigate. But i guess that will make more and more sense with more experience

2020-09-29 17:42 UTC, jespa374 approved these changes
Great design! Simple and clean! Your code is really clean, well-structured and easy to read and follow with your comments. Great job! You have achieved both blue and red level goals! :) You can do the changes that I have proposed when you have the time but otherwise job well done! :)

2020-09-29 17:42 UTC, jespa374 commented on index.html
> +            <div class="cityName" id="name"></div>
I think you should write class names and ID names in kebabcase in HTML & CSS

2020-09-29 17:42 UTC, jespa374 commented on index.html
> +        <!--Todays Weather in different cities-->
Great that you have comments which makes it easier for the reader :)

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +const apiUrlForecast = `https://api.openweathermap.org/data/2.5/forecast?q=Stockholm,Sweden&units=metric&APPID=${apiKey}`;
Good that you assign the API url and the API key to variables. Looks really clean this way and very organized :)One thing is that I think the convention is to write URLs like API_URL instead of camelcase

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +const forecastContainer = document.getElementById('forecast')
Really good that you assign your document.getelementids to variables :)

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +    .catch((error) => {
Good that you have .catch(error) to see if there's an error :)

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +
some unnecessary space here

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +            document.getElementById('forecastIcon').innerHTML += `<img src=http://openweathermap.org/img/wn/${item.weather[0].icon}@2x.png></img>`
Here you could have assigned these document.getelementbyids to variables

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +        console.log(json)
You can remove the console.log

2020-09-29 17:42 UTC, jespa374 commented on script.js
> +        console.log(json)
Remove the console.log

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +    font-family:'Raleway', Sans-Serif;
Good that you have a fallback font here in case the first doesn't work :)

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +
Unnecessary spacing or inconsistent with the line of spacing

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +#todaysWeatherIcon img {
You should avoid using IDs in styling. Use class instead

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +.temperature{
Should be space before the {

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +#favouriteCityAll {
Use class

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +#todaysWeatherIconOslo img, #todaysWeatherIconAlicante img , #todaysWeatherIconBerlin img{
Maybe you could add one class and apply the same class to  all of these elements

2020-09-29 17:42 UTC, jespa374 commented on style.css
> +@media screen and (min-width: 1024px) {
The min-width here should be 1025px since you have max-width 1024 px in the previous media query.

2020-10-15 08:21 UTC, EmOlsz requested changes
Good job Moa! Your code is pretty consequent and without any crucial errors. Your CSS styles are well done, same goes for HTML.
Still, some things needs to be fixed - take a look on my comments and provide changes

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> +    .then((Response) => {
We shouldn't write `Response` in capital letters - right now, during React week, I hope you understand why.
Moreover, you don't need to wrap this argument in one extra parentheses, we don't have to do that if we have only one argument

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> +        console.log(json)
Before final push, we should delete all console.logs

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> +    .catch((error) => {
Very good :)

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> +        console.log(error)
One tip for you - we have special `console` for errors, it's called `console.error()`. It does exactly same thing as normal `console.log()`, but has red background

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> +        const filteredForecast = json.list.filter(item =>
Wrong indentation

2020-10-15 08:21 UTC, EmOlsz commented on script.js
> + const AlicanteIcon = document.getElementById('todaysWeatherIconAlicante');
once again, capital letter

2020-10-15 08:21 UTC, EmOlsz commented on style.css
> +
Exactly

2020-10-15 08:21 UTC, EmOlsz commented on style.css
> +#todaysWeatherIcon img {
Agree

2020-10-15 08:21 UTC, EmOlsz commented on style.css
> +.temperature{
Agree

2020-10-15 11:29 UTC, mhammarback commented
Thank you both for your code reviews! 
I have implemented your requested changes here is a summarize: 
- Indentation fixed 
- Capital R in response changed to small r 
- Capital A changed to small a 
- No CSS styling on ID, changed to class
-  catch error have console.error()

2021-02-16 17:53 UTC, closed without merging