Weather app by Mats Johansen
Technigo/project-weather-app pull request #117
Opened 2020-09-27 08:42 UTC by mats-johansen

Link to my deployed project:
https://affectionate-montalcini-013f2d.netlify.app

My reflections on how this week's project turned out:
Turned out the way I thought it would look like but did not feel satisfied because of lack of time to code. I wanted to include more cities weather and change the background color to reach the red level but work got in the way.

2020-10-01 07:30 UTC, emma-tech reviewed
Really good job with your weather app Mats! You have a lot of knowledge in writing good and clean code at it really shows in this assignment. 🥇 

Even though you felt that you wanted to do more with the assignment (I can relate to that, never feel that there is enough time to do everything you want to do :D) this knowledge of understanding the basics and how to write simple and clean code means everything for the future. So good job, be proud of yourself! 🌟 👏

2020-10-01 07:30 UTC, emma-tech commented on README.md
> +I struggled a bit with understanding APIs so I kept this project very simple to understand the concept of APIs. If I had more time I would add a function where the user could search for the weather a
Same for me! Really good that you focused on understanding the basics at this point, it will help you a lot in the future! 👍

2020-10-01 07:30 UTC, emma-tech commented on README.md
> +https://affectionate-montalcini-013f2d.netlify.app
I love it 😍 clean and simple design! Love the symbol and the beautiful gradient color as well

2020-10-01 07:30 UTC, emma-tech commented on code/index.html
> +<!DOCTYPE html>
Nicely written HTML-code, clean and simple 👍

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +// API
WOW. So well structured and easy to read. Really good that you comment different sections as well. Good job! 👍

2020-10-01 07:30 UTC, emma-tech commented on code/style.css
> +body {
Same here, very nicely written CSS-code. Well structured and easy to read :)

2020-10-01 07:30 UTC, emma-tech commented on code/icons/clouds.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="77.194" height="53.261" viewBox="0 0 77.194 53.261">
Interesting! I've never worked with svg - images before :)

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +  "https://api.openweathermap.org/data/2.5/weather?q=göteborg&units=metric&APPID=22db637cf647bcd1513c052513b7d54c";
Even though the app only shows one city at the moment, you could've put the city in a variable as well from the beginning, makes it easy to update and change if you want to continue working and develop the app with a search-function for more cities and so on :) But this is of course easy to change later on! :) 

A separate variable for the api-key is a good idea as well ( I know that the function with hiding the key didn't really work for this particular assignment, but I think it's good knowledge to take with us for the future :)

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +fetch(apiToday)
👏

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +      if (json.weather[0].main === "Clear") {
👏

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +      const sunriseTime = sunrise.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
Nice work with showing the time correctly!

2020-10-01 07:30 UTC, emma-tech commented on code/script.js
> +    filteredForecast.forEach((day) => {
👏

2020-10-01 07:32 UTC, emma-tech approved these changes
APPROVED ⭐

2020-10-15 12:44 UTC, EmOlsz requested changes
Hey Mats, good job! Your project met basic requirements :) It looks and works in a nice way.
Before I will approve your project, please, change variables cloudImg, rainImg etc. to strings and remember about changing their occurrence in weatherImg function!

2020-10-15 12:44 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="style.css">
Let's not forget about `./` in path to file

2020-10-15 12:44 UTC, EmOlsz commented on code/index.html
> +  <script src="script.js"></script>
`./`

2020-10-15 12:44 UTC, EmOlsz commented on code/script.js
> +    };
Is there a good reason why you used objects over here? Simple string variable would be enough :)

2020-10-15 12:44 UTC, EmOlsz commented on code/script.js
> +  .then((response) => {
No need for extra set of parentheses over here, we are passing only one argument so we don't need them

2020-10-19 06:55 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging