Weather App - Destiny
Technigo/project-weather-app pull request #119
Opened 2020-09-27 13:03 UTC by destinyleia

Link to my deployed project:
https://stoic-liskov-800c94.netlify.app/

My reflections on how this week's project turned out:
Read my read me

Things I'd like to have clarified or explained in more detail:
More about how to write JavaScript so it works with html - their connection

2020-09-28 17:25 UTC, AxelHammarback reviewed
Destiny, nicely done! I've followed the process in the hippo Slack channel, and you've made incredible progress. All in all, I think you did a really good job with the app. On my macbook, the today's temperature is covered by the weather image, but it looks good on mobile 👏

2020-09-28 17:25 UTC, AxelHammarback commented on index.html
> +      </section>
Really nice that you're adding alt texts to your images – helps if you use a screen reader. Keep it up! 

Also, nice work with camelCase for the id's. But for classes, try to use kebab-case (like the [Technigo guidelines]([https://www.notion.so/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e](https://www.notion.so/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e)) proposes). But the naming of them is good!

2020-09-28 17:25 UTC, AxelHammarback commented on index.js
> +const fetchWeatherToday = 'https://api.openweathermap.org/data/2.5/weather?q=Stockholm,Sweden&units=metric&APPID=f2f9f8b681a8d2ef3cd9a12ebdc8c363';
Really nice that you declare these variables from the start. Makes it easy to follow.

2020-09-28 17:25 UTC, AxelHammarback commented on index.js
> +        todaysImage.src = `./images/${todaysImageId}.gif`;
👏 I didn't figure out how to use the icons from the API, but now I know! Thanks :)

2020-09-28 17:25 UTC, AxelHammarback commented on index.js
> +};
Nicely written, makes it easy to understand what's happening 👍

2020-09-28 17:25 UTC, AxelHammarback commented on index.js
> +            const filteredList = nextWeeksWeatherInfo.list.filter(item => item.dt_txt.includes('12:00'));
This seems like a very smart way to filter the list – mine was way more complicated 😅

2020-09-28 17:25 UTC, AxelHammarback commented on style.css
> +}
A small tip here: you can write the following:

`h1, h2, h3, h4, h5 {
font-family: 'Trebuchet MS', [...]`

That way you can remove the Trebuchet MS from the other places. Plus, if you want to change your font you only have to do it in one place, rather than five.

2020-09-28 17:25 UTC, AxelHammarback commented on style.css
> +  }
A tip: In the media query, you only need to specify the exclusive settings. So, if you have `font-family: arial` in the base CSS code, you don't need to add it to the media query. I think it will save a bunch of space here :)

2020-10-15 14:05 UTC, EmOlsz requested changes
Hello Destiny! In general your project is well done, data is queried properly and passed to HTML in a nice way :)
Still, there are some things you should change - take a look on my comments and provide changes

2020-10-15 14:05 UTC, EmOlsz commented on style.css
> +  font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
Font-family property should be declared in body or html, not in each element

2020-10-15 14:05 UTC, EmOlsz commented on style.css
> +#nextWeeksWeatherId {
We shouldn't style by id's

2021-01-04 09:24 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging