Sannas weather app
Technigo/project-weather-app pull request #122
Opened 2020-09-27 15:10 UTC by sannadw

**Link to my deployed project:** 
https://sannasweatherapp.netlify.app/

**My reflections on how this week's project turned out:**
Im happy I got the API to work, but I wish I had much more time to make it look better. 

**Things I'd like to have clarified or explained in more detail:**
My code does not look very clean. When showing different images depending on the weather I added a lot of code in my if else statement. Im sure this can be done in a prettier way.

2020-10-02 18:19 UTC, rebkova reviewed
Sanna, your code is clean and easy to read. You know how to fetch the data from an API and display it in a required format. In addition, your page is responsive. Nice job on this week's project.  Keep it up!

2020-10-02 18:19 UTC, rebkova commented on script.js
> +            setWeatherImages()
Super clean and easy to understand.

2020-10-02 18:19 UTC, rebkova commented on script.js
> +                } else if (weatherType === 'Rain' || weather.main === 'Drizzle') {
Any specific reason why you used weather.main instead of weatherType in the second operand?

2020-10-02 18:19 UTC, rebkova commented on index.html
> +    <div class="tablet-weatherandimage">
To follow the naming convention, you could write the class name as: tablet-weather-and-image.

2020-10-02 18:19 UTC, rebkova commented on index.html
> +  <link rel="stylesheet" href="./style.css" />
Very nice, including ./ in your paths! :)

2020-10-15 14:55 UTC, EmOlsz requested changes
Good job this week Sanna! Your app looks very nice, code in general is also well done :)
Still, there are some things that needs to be fixed. Take a look on my comments and provide changes, after that I will be able to approve your project!

2020-10-15 14:55 UTC, EmOlsz commented on index.html
> +  <link rel="stylesheet" href="./style.css" />
:)

2020-10-15 14:55 UTC, EmOlsz commented on script.js
> +    .then((response) => {
No need to wrap `response` in extra pair of parentheses, since it's only one argument we can omit them

2020-10-15 14:55 UTC, EmOlsz commented on script.js
> +                    cloudImage.classList.add("visible");
We shouldn't design our code logic like that - there is just too much of code.
You could just have one HTML element (maybe image?) and pass to it new value as `src`. Thanks to that we won't have to write 6 lines of code in each statement.
This needs to be changed

2020-10-15 14:55 UTC, EmOlsz commented on script.js
> +
There is a lot of places like this in your code - please, go through whole project and delete empty lines

2020-10-15 14:55 UTC, EmOlsz commented on style.css
> +    padding-top: 4px;
Haha, good :D

2020-10-15 14:55 UTC, EmOlsz commented on style.css
> +    border-bottom: 0px;
`border-bottom: 0;`

2020-10-15 14:55 UTC, EmOlsz commented on style.css
> +#city {
We shouldn't style by id's, let's change it to class

2021-02-18 12:00 UTC, closed without merging