Project: Weather App - Jamie Cook
Technigo/project-weather-app pull request #123
Opened 2020-09-27 15:11 UTC by the-j-curl

Link to my deployed project:
https://project-weatherapp.netlify.app/

My reflections on how this week's project turned out:
While I enjoyed learning about API's and JSON, I also found it tough to get started in this weeks project. I feel that I understood the fetch function and how to access the data, but knowing how to capture it and then manipulate it using functions provide to be confusing.

Things I'd like to have clarified or explained in more detail:
How to plan my JavaScript so that I know what functions are required, and how they will all link up together.

2020-09-29 18:03 UTC, sarahejhej requested changes
I'm really impressed by your project this week Jamie, I know you had a late and stressful start. You must have put a lot of effort into it this weekend, bravo! Your code is clean and structured, it's easy to read and understand. Your class and id naming seem well thought out and you use semantic HTML tags. The design is really clean and I like the cards you made for the weather forecasts! The page is also responsive and designed mobile first  👍

There seems to be duplicates of some of the files, I think you could delete all the extra files and folders. The indentation is mostly consistent, but consider changing it to 2 spaces. It's easy to change the formatting settings in VS code to auto format. And in the HTML file there were a mix of 2 and 4 spaces, please chose one and be consistent. Also remove the console.logs that were left. That's all to be done before being approved! 😄🏅

2020-10-01 08:57 UTC, the-j-curl commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
The 4 space indentation was automatically generated by visual code. I wonder if there is a setting to change this?

2020-10-01 09:12 UTC, the-j-curl commented on index.html
> +        <p id="sun-times" class="sun-times"></p>
Yes good point. I have updated to main-temperature

2020-10-01 09:13 UTC, the-j-curl commented on index.html
> +        </nav>
Again, auto indentation from VS. Not sure why. Corrected

2020-10-01 09:17 UTC, the-j-curl commented on style.css
> +    font-family: 'Kumbh Sans', sans-serif;
I was being greedy there! I think this was where I was testing different fonts.
One has now been removed. Thanks

2020-10-01 09:19 UTC, the-j-curl commented on style.css
> +    background-position-y: 60%;
Yes this is quite useful when you want to have more control over the background image. For example, some parts of this image show's a lot of cloud, which meant that my white text did not stand out enough.

2020-10-01 09:19 UTC, the-j-curl commented on style.css
> +}
Good spot

2020-10-01 09:25 UTC, the-j-curl commented on style.css
> +    flex-direction: row;
Yes correct. Is it good practise to specify it though anyway? I'm not sure.
Maybe a question for a code coach.

2020-10-01 09:25 UTC, the-j-curl commented
Thanks for your feedback Sara. I always appreciate other peoples thoughts and comments, and yours have been useful.
I have completed the changes and pushed them to github.

2020-10-01 10:29 UTC, the-j-curl commented on script.js
> +       const city = `${todaysResults.name}`;
Yes, I think you're right. Updated

2020-10-01 10:30 UTC, the-j-curl commented on script.js
> +       containerSunTimes.innerHTML += `Sunrise: ${sunrise} | Sunset: ${sunset}`;
Removed

2020-10-01 10:30 UTC, the-j-curl commented on script.js
> +                    console.log(day, iconSrc, temperature, feelsLike);
Removed

2020-10-01 10:30 UTC, the-j-curl commented on script.js
> +                    console.log(item);
Removed

2020-10-01 10:31 UTC, the-j-curl commented on script.js
> +const setDayDate = (day) => {
Yes I agree - updated

2020-10-01 10:32 UTC, the-j-curl commented on style.css
> +    flex-direction: row;
Cool. In that case I have removed this line

2020-10-01 12:31 UTC, sarahejhej approved these changes

2020-10-16 07:54 UTC, EmOlsz approved these changes
Good job Jamie, I really had hard time trying to find things in your code which could be improved :) Keep it this way!
I've added some small 4 comments, take a look on them!

2020-10-16 07:54 UTC, EmOlsz commented on script.js
> +const API_URL2 = `https://api.openweathermap.org/data/2.5/forecast?q=Stockholm,Sweden&units=metric&APPID=${API_KEY}`;
`API_URL_WEATHER` and `API_URL_FORECAST` as names would be better. Numbers in variable names are not very descriptive

2020-10-16 07:54 UTC, EmOlsz commented on script.js
> +    return Math.round(number * 10) / 10;
Nice job :)

2020-10-16 07:54 UTC, EmOlsz commented on style.css
> +    background-image: url(./assets/sky-day.jpg);
Let's try to wrap url inside quotes - some browsers might have problem with reading url without them :

```
background-image: url("./assets/sky-day.jpg");
```

2020-10-16 07:54 UTC, EmOlsz commented on style.css
> +    color: #ffffff;
We can simplify this : `#fff`

2021-02-16 17:53 UTC, closed without merging