Weather in Stockholm - Ingela Löfgren
Technigo/project-weather-app pull request #124
Opened 2020-09-27 15:14 UTC by IngelaL

Link to my deployed project: https://weatherinstockholm.netlify.app/

My reflections on how this week's project turned out: I would have made more on this project but unfortunatley other things (personal issues) came in between.

Things I'd like to have clarified or explained in more detail: not really.

2020-09-29 18:07 UTC, HenrikeW requested changes
You wrote really clean code that was easy to read and follow. Very structured and straight forward, great! :) I commented some smaller issues regarding semantics or naming conventions that you can have a look at if there is time. Otherwise, I think you should add some more responsiveness to fulfill the blue requirements. But still, with regards to the little time you had and your personal situation right now, you did a really good job! Thumbs up 👍

2020-10-02 11:49 UTC, IngelaL commented
Great review Henrike. It gave me a lot to reflect on and to learn from. I have now made the site more responsive which was a change request.  Thank you!

2020-10-16 08:37 UTC, EmOlsz approved these changes
Nice project Ingela, good job! You've done basic requirements in a very nice, clean way. Congratulations ;)
Take a look on my comments, they might help you improve even more!

2020-10-16 08:37 UTC, EmOlsz commented on index.html
> +    <link rel="stylesheet" href="style.css" />
Let's not forget about `./` in path to file

2020-10-16 08:37 UTC, EmOlsz commented on index.html
> +<script src="script.js"></script>
`./`

2020-10-16 08:37 UTC, EmOlsz commented on script.js
> +const weatherApi = "https://api.openweathermap.org/data/2.5/weather?q=Stockholm,Sweden&units=metric&APPID=1c055fa282f5d9954e97fd78b7cd3c03";
👍

2020-10-16 08:37 UTC, EmOlsz commented on script.js
> +    forecastDayAndTemp.innerHTML += `<h5>${dayName}: ${dayTemperature} °C</h5>`;
Definitely, good catch Henrike :)

2020-10-16 08:37 UTC, EmOlsz commented on style.css
> +h1 {
You could use more CSS classes, consider it for the next time :)

2020-10-16 08:37 UTC, EmOlsz commented on style.css
> +body {
Wrong indentation

2020-10-16 08:37 UTC, EmOlsz commented on style.css
> +  background-image: url(/weatherBackgroundTablet.jpg);
Let's try to wrap url inside quotes - some browsers might have problem with reading url without them :

```
background-image: url("/weatherBackgroundTablet.jpg");
```

2020-10-16 08:37 UTC, EmOlsz commented on style.css
> +@media (min-width:1024px) {
Wrong indentation inside this `@media` as well

2021-02-16 17:53 UTC, closed without merging