Weather App
Technigo/project-weather-app pull request #128
Opened 2020-09-27 17:22 UTC by JHarde

Link to my deployed project: https://stockholmweather.netlify.app/

My reflections on how this week's project turned out: This wasn't my best week, struggled a lot due to lack of time because of work and had a hard time figuring some things out. I would like to make my app better later on and strive towards red and black level. 

Things I'd like to have clarified or explained in more detail:

2020-09-30 14:42 UTC, LillanEriksson approved these changes
The page looks good Joel, and I totally understand that you had a timeshort this week. and I think you have reached the blue level.

2020-09-30 14:42 UTC, LillanEriksson commented on Code/script.js
> +
Very neat and readable code Joel!

2020-09-30 14:42 UTC, LillanEriksson commented on Code/script.js
> +
I have really nothing to comment about, except that you could have put more into different functions.

2020-09-30 14:42 UTC, LillanEriksson commented on Code/style.css
> +
The responsivity looks great on the live page, you did a great job with that!

2020-09-30 14:42 UTC, LillanEriksson commented on Code/style.css
> +}
I think it's preffered to style by class and stick with that, and not mix styling ids and classes. I think the coaches have mentioned this during some lectures too.

2020-10-16 13:03 UTC, EmOlsz approved these changes
Nice project Joel, congratulations! It's working (so that's most important) and looking good. Nonetheless, I see that your code starts to be messy - it seems that you haven't checked it before final push.
Almost all of my comments are about possible improvements, please consider them as very important, because time to change some tendencies of yours is right now (and will end soon as they will change from tendencies to habits). Provide those changes and then I'll approve your project.
Apart from that, as I said, good job :)

2020-10-16 14:28 UTC, EmOlsz requested changes
Changes requested

2020-10-19 12:33 UTC, JHarde commented
Hi Maks!

I have looked through the changes you requested and tried my best to fix them. Regarding the indentation I have tried to use "Prettier" but for some reason it doesn't seem to work for me in this project. Worked well last week. Feel free to let me know more in detail how I can change this if changes still need to be made.

2020-10-20 19:03 UTC, EmOlsz commented
> Hi Maks!
> 
> I have looked through the changes you requested and tried my best to fix them. Regarding the indentation I have tried to use "Prettier" but for some reason it doesn't seem to work for me in this project. Worked well last week. Feel free to let me know more in detail how I can change this if changes still need to be made.

Hey Joel! Thank you for quick changes, everything is ok now :)
Regarding Prettier - well, shit happens unfortunately. This software is not intuitive at all and breaks a lot. You don't have to worry about that in this case!

2020-10-20 19:03 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging