weather-app Sara Stjernberg
Technigo/project-weather-app pull request #130
Opened 2020-09-27 17:49 UTC by stjernberg

Link to my deployed project:
https://pensive-darwin-b3e353.netlify.app/

My reflections on how this week's project turned out:
 I didn't have time to finish all I wanted to do, du to lack of time this week

Things I'd like to have clarified or explained in more detail:
How to display multiple icons in the fiveday forecast.

2020-09-30 14:33 UTC, mats-johansen approved these changes
What I can see you did you did the blue requirements with no problem at all and you also came very far on the red section. I could see a small error when opening your page, there is a small screen on the right hand side but it doesn't do anything do mess with the functions of the weatherapp so it is just as i said, a small error. 

The searchfunction was awesome, great job on that! I commented in your code about the problem that when using the searchfunction, it just keeps addings data ontop of the already fetched data on the dom and it get's kind of messy after a few citys. It also changes the viewheight of the page after a while. But i believe that it is a really small change that is needed to get that sorted. 

Overall I think you do a great job with keeping your code consistent and it shows when reading your code. 

The blue level is reached as it now and with a few changes you are at the red level!
Keep up the good work!

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +});
Great job coding this function!

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +    document.getElementById('sunrise').innerHTML += sunriseTimeString;
Nice short code for the sunrise- and sunset-time

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +    const months = ["January", "Febrary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
Nice touch adding the date to the todays forcast!

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +    weatherPic.src = `./assets/${weatherPicID}.png`;
adding an alt can be good if the picture doesnt work

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +            console.log(filteredArray);
remove console.logs when the code is finished

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +                document.getElementById('description').innerHTML += `<p>${weatherType}</p>`;
Once you enter a citys name and get the weather for example, Malmö, and then search on Gothenburg you get Gothensburgs weather added onto Malmös weather. So the list on the weekly forcast, sunrise- & sunset-times just add on. I did not to this myself but I am sure you could ask one of the codecoaches how exactly to do this. 

One thing you can test is to just write document.getElementById('temp').innerHTML (WITHOUT THE + SIGN BEFORE THIS -->)= `<p>${temperature} °C  &nbsp &nbsp</p>`;

2020-09-30 14:33 UTC, mats-johansen commented on style.css
> +        }
The styling looks great overall!

2020-09-30 14:33 UTC, mats-johansen commented on script.js
> +                const weatherType = forecast.weather[0].description
;

2020-10-16 14:47 UTC, EmOlsz requested changes
Hey Sara! Your code looks very nice, I'm impressed by amount of extra requirements :)
Some things can be improved, that's why I changed status to Changes requested. Please, provide changes and then I will accept it.
Moreover, I had problem with displaying your site - netlify link doesn't seem to work. Please, fix that as well :)

2020-10-16 14:47 UTC, EmOlsz commented on index.html
> +    <link rel="stylesheet" href="style.css">
Let's not forget about `./` in path to file

2020-10-16 14:47 UTC, EmOlsz commented on index.html
> +            <h2>
Wrong indentation

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +import { API_KEY } from './api.js';
Good job :)

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +    if (navigator.geolocation) {
Great achievement!

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +input.addEventListener('keypress', function(e) {
It should rather be like this : `input.addEventListener('keypress', e => { ... }`

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +
We could also add some log to console about the error like that :

```
console.error(error);
```

As you can see, I used new `console.error()` type. It works the same as `console.log()`, but also adds red background to the message in Console tab indicating that something went wrong

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +        });
Missing `catch()`

2020-10-16 14:47 UTC, EmOlsz commented on script.js
> +geoLocate()
You seem to miss semicolons in some places

2020-11-02 12:47 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging