Weather app
Technigo/project-weather-app pull request #131
Opened 2020-09-27 17:58 UTC by moablomkvist

Link to my deployed project:
betterweathernosweather.netlify.app

My reflections on how this week's project turned out:

I learn things all the time. But since I work at the same time and have a two-year-old who constantly takes my attention, there is not as much time left as I would like. It feels like I never have time to do red and black level. I hope I can advance further in the course.

Things I'd like to have clarified or explained in more detail:

2020-09-30 15:42 UTC, johannarexin commented on code/index.html
> +</footer>
Nice with a personal footer :)

2020-09-30 15:42 UTC, johannarexin commented on code/script.js
> +//const weatherSunset = document.getElementById('sunset');
Maybe these two can be deleted?

2020-09-30 15:42 UTC, johannarexin commented on code/script.js
> +
Delete this lines?

2020-09-30 15:42 UTC, johannarexin commented on code/script.js
> +const apiWeek = 'https://api.openweathermap.org/data/2.5/forecast?q=Stockholm,Sweden&units=metric&APPID=e33f1cc192401277e601a6aed3a82800'
Maybe put this link in the top? Below the apiToday link. For me it would be easier to read the code that way.

2020-09-30 15:42 UTC, johannarexin commented on code/style.css
> +}
Really clear and good styling :) Good job!

2020-10-16 15:02 UTC, EmOlsz requested changes
Nice project Moa :) I'm new fan of your design! Moreover, you JS code is clean and consistent, good job!
Still, there are some things that you should fix. Take a look on my comments and provide some changes, after that I will approve you project!

2020-11-10 18:41 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging