Simple Weather App
Technigo/project-weather-app pull request #132
Opened 2020-09-27 18:10 UTC by pwangy

Link to my deployed project:
https://pwangy-weather.netlify.app/

My reflections on how this week's project turned out:
This is all in  my ReadMe below. :)

2020-09-30 15:27 UTC, monkeybusiness101 requested changes
Please update the PR with the correct files that should be reviewed. I will do a review again when this is done. /Max

2020-09-30 15:27 UTC, monkeybusiness101 commented on README.md
> -# Weather App
Hi Peggy! I like your readme a lot. It explains the different challenges you had, different areas of js that you worked with, and learned more about. I also like that you show what level you completed 👍

2020-09-30 15:27 UTC, monkeybusiness101 commented on blue_lvl/index.html
> +</body>
Clean code and easy to go through 👍

2020-09-30 15:27 UTC, monkeybusiness101 commented on blue_lvl/script.js
> +const apiNow = `http://api.openweathermap.org/data/2.5/weather?id=${stockholm}&units=metric&appid=eb46c8c17530a3d02461794022d39d32`
I like that you create variables of reusable components. Perhaps there are more data that you can make into variables, f.e apikey?

2020-09-30 15:27 UTC, monkeybusiness101 commented on blue_lvl/script.js
> +    })
I was struggling with conversion and your code saved my life, thank you for that!

2020-09-30 15:27 UTC, monkeybusiness101 commented on blue_lvl/script.js
> +})
I did a similar fetch like you. Now when we have worked with APIs a bit more, I would recommend (to myself as well) to try to break out components into separate functions. In this case, perhaps a function that fetch data? One function that manipulates the DOM with innerHTML? In the long run, you want to aim for functions that can be reused for other scenarios, and that is not too specific.

2020-09-30 15:27 UTC, monkeybusiness101 commented on index.html
> +<!DOCTYPE html>
Why is there several index, js, css files? Please be mindful that it can be hard to make a review when there are several files of the same purpose.

2020-09-30 15:48 UTC, pwangy commented
Hi @monkeybusiness101 ! You might notice that some of the file are in a folder called "blue_lvl". Please ignore those and review the files not in the folder which is the final version. Hope that helps clear things up.

2020-10-01 06:58 UTC, monkeybusiness101 approved these changes

2020-10-01 06:58 UTC, monkeybusiness101 commented on index.html
> +<!DOCTYPE html>
I will review the rest of the files now

2020-10-01 06:58 UTC, monkeybusiness101 commented on index.html
> +    </div>
Be mindful of how you label classes and IDs. I can understand that now means now but perhaps label it similar to the Img class "today"?

2020-10-01 06:58 UTC, monkeybusiness101 commented on script.js
> +]
Nice use of putting the cities into an array that is then populated depending on the index of the dropdown!!

2020-10-01 06:58 UTC, monkeybusiness101 commented on script.js
> +getForecast()
Good commenting and use of onload

2020-10-04 13:14 UTC, pwangy commented on index.html
> +    </div>
went through and clean my ID tags to be consistently camelcase. also updated this class to be "icon" since the class was made to style the icon's display size.

2020-10-19 07:58 UTC, EmOlsz requested changes
In general your project is well done Peggy, good job! Nonetheless, there are things you need to fix - as I can see, your code is a bit messy, fix stuff pointed out in my comments and try to remember about them for future projects.
Moreover, your app is not responsive and this is basic requirement - needs to be done

2020-10-19 07:58 UTC, EmOlsz commented on blue_lvl/script.js
> +fetch(apiNow)
You could also add `catch()` method after second `then()` to detect any possible errors:

```
const myFunction = () => {
  fetch(API)
    .then(response => {
      return response.json();
    })
    .then(weatherToday => {
      do your stuf...
    })
    .catch(err => {
      console.error(err);
    });
};
```

As you can see, I've also used new console, `console.error()`. It does same thing as `console.log()`, but also adds red background to the message in Console tab indicating that something went wrong

2020-10-19 07:58 UTC, EmOlsz commented on blue_lvl/script.js
> +})
Agree, it could be done like this

2020-10-19 07:58 UTC, EmOlsz commented on blue_lvl/style.css
> +  /* border-left: 1px solid navy; */
Let's delete all commented code

2020-10-19 07:58 UTC, EmOlsz commented on blue_lvl/style.css
> +  flex: none;
Is there any reason you use this property over here? It doesn't do anything

2020-10-19 07:58 UTC, EmOlsz commented on script.js
> +
Empty line - let's delete it

2020-10-19 07:58 UTC, EmOlsz commented on script.js
> +    fiveDay.innerHTML = null
If you want to clear html of any element, you should set it to empty string, not to null

2020-10-19 11:11 UTC, pwangy commented on blue_lvl/style.css
> +  /* border-left: 1px solid navy; */
removed this.

2020-10-19 11:22 UTC, pwangy commented on blue_lvl/script.js
> +fetch(apiNow)
updated this.

2020-10-19 11:25 UTC, pwangy commented on blue_lvl/style.css
> +  flex: none;
removed these lines.

2020-10-19 11:27 UTC, pwangy commented on script.js
> +
done

2020-10-19 11:28 UTC, pwangy commented on script.js
> +    fiveDay.innerHTML = null
updated this.

2020-10-19 13:20 UTC, pwangy commented
Added responsiveness.

2020-10-19 13:23 UTC, pwangy commented
I've cleaned up the code and made suggested edits.

2020-10-20 19:04 UTC, EmOlsz approved these changes

2020-10-22 09:21 UTC, closed without merging