Simple Weather App by Amanda :)
Technigo/project-weather-app pull request #134
Opened 2020-09-27 19:20 UTC by amandaflod

Link to my deployed project:

https://elastic-blackwell-e78f71.netlify.app/

My reflections on how this week's project turned out:

I think it turned out quite well in the end, but it was a long way to get there and a lot of getting stuck on the way. I was too ashamed of my code to commit any changes earlier than today, as even I could not make sense of what I had written. But I think that I have learned a lot this week, especially when it comes to cutting down on the code and trying to make it as readable and clean as possible!

Things I'd like to have clarified or explained in more detail:
Nothing I can think of right now :)

2020-09-30 16:25 UTC, lindahz approved these changes
Amanda, I am so impressed by your code! 😍  It was really hard to give you any constructive feedback, especially since you managed to keep your code SUPER clean and structured. I love the clean design, colors and the nice gradient background you picked.

Your javascript was also a bit different from mine, and I am happy I got the chance to learn some other ways of writing the code. I can see that you spent time to really understand the code, because it looks well thought out.

 I only have a few comments as you can see.

Great job!!! ❤️⭐️

2020-10-19 09:22 UTC, EmOlsz requested changes
Good job Amanda! Your project is very clean, you also use a lot of good practices such as lack of parentheses around one argument in function declaration, `catch()` method in fetch and shorthand for arrow functions. Congratulations :)
I've added few comments, please provide changes according to them

2020-10-19 09:22 UTC, EmOlsz commented on script.js
> +    console.error(error)
Great job with `console.error()`!

2020-10-19 09:22 UTC, EmOlsz commented on script.js
> +  shortForecastDay = forecastDay.substring(0, 3)
You didn't use `const`, `let` or `var` keyword and by mistake you created global variable - this is huge antipattern, please fix that

2020-10-19 09:22 UTC, EmOlsz commented on style.css
> +  #forecastList {
Even more - we should use only classes, no id's

2021-03-11 09:14 UTC, closed without merging