Pull request info
Technigo/project-weather-app pull request #137
Opened 2020-09-27 20:19 UTC by Katsiez

Link to my deployed project:
Coming up shortly in the README file. 

My reflections on how this week's project turned out:
Difficult, I struggled a lot, cried, and drank a lot of wine. But it's okay, I still somehow managed to create a somewhat decent app.  

Things I'd like to have clarified or explained in more detail: 

For this project, I attempted to change my forecast and current weather URLs by replacing the city name to a variable called 'city' and the API key digits to 'apiKey', both previously defined. Each time I tried to do this, either forecast or current weather would rebel and not display the data.
I am therefore not expecting this app to be properly displayed on Netlify and this project will instead have to be run through running the index.html file.

-This is what I would like to clarify.

2020-09-28 04:08 UTC, ankimelin approved these changes
Would have loved to see the live weather app, but no link included yet - reviewed only the code and not the req. 

So cool you managed the changed background and adding a city! Love the small comments which makes it easy to understand the purpose of the code.

As always - great work!!

2020-09-28 04:08 UTC, ankimelin commented on code/weather.js
> +            currentWeatherToday(json)
I like that you call a function here!

2020-09-28 04:08 UTC, ankimelin commented on code/weather.js
> +    const forecastIcon = document.getElementById('forecastIcon')
Should these also have been declared at the top?

2020-09-28 04:08 UTC, ankimelin commented on code/weather.js
> +    .then((data) => { updateMinMaxTemps(data) })
Should this be moved further up?

2020-10-19 10:23 UTC, EmOlsz requested changes
In general it's well done project, congrats Katarina! Still, there are some things you need to change. They are mostly bad habits you probably didn't get rid of, so consider them (from now on) as a super important thing to pay attention for.
Provide changes and I will approve your project!

2020-10-19 10:23 UTC, EmOlsz commented on code/index.html
> +      <div class id="city">
No need for empty `class` attribute

2020-10-19 10:23 UTC, EmOlsz commented on code/index.html
> +      <div class="highLow">
classes should be written in `kebab-case`, not `camelCase`

2020-10-19 10:23 UTC, EmOlsz commented on code/index.html
> +        <p>Sunrise: <img src="./assets/sunrise.png" style="width: 20px" /></p>
Width of an image should be defined in CSS, not in HTML

2020-10-19 10:23 UTC, EmOlsz commented on code/style.css
> +  margin: 50px 50px;
`margin: 50px` is shorthand

2020-10-19 10:23 UTC, EmOlsz commented on code/style.css
> +#temperature {
We shouldn't style by id's at all, always use classes

2020-10-19 10:23 UTC, EmOlsz commented on code/style.css
> +  background-image: url(./assets/cold.jpg);
It's more safe to wrap url around quotes - some browsers might have problem with reading path without them 

```
background-image: url("./assets/cold.jpg");
```

2020-10-19 10:23 UTC, EmOlsz commented on code/weather.js
> +
empty line

2020-10-19 10:23 UTC, EmOlsz commented on code/weather.js
> +    .then((response) => { return response.json() })
You don't need to write `return` keyword and brackets if it's same line :

```
.then(response => response.json())
```

2020-12-04 13:12 UTC, Katsiez commented
And here is the other one!
https://github.com/Technigo/project-weather-app/compare/master...Katsiez:master
:)

On Mon, Oct 19, 2020 at 12:24 PM Maksymilian Olszewski <
notifications@github.com> wrote:

> *@EmOlsz* requested changes on this pull request.
>
> In general it's well done project, congrats Katarina! Still, there are
> some things you need to change. They are mostly bad habits you probably
> didn't get rid of, so consider them (from now on) as a super important
> thing to pay attention for.
> Provide changes and I will approve your project!
> ------------------------------
>
> In code/index.html
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507627841>
> :
>
> > +  <head>
>
> +    <meta charset="UTF-8" />
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>
> +    <title>Project 6: Weather App</title>
>
> +    <link rel="stylesheet" href="./style.css" />
>
> +  </head>
>
> +
>
> +  <body>
>
> +    <!-- MAIN SECTION, CURRENT WEATHER -->
>
> +    <section class id="weather-wrap">
>
> +      <h1>Toronto Forecast</h1>
>
> +    </section>
>
> +
>
> +    <section class="main">
>
> +      <img class="cn-img" src="./assets/cntower.png" height="100px" />
>
> +      <div class id="city">
>
>
> No need for empty class attribute
> ------------------------------
>
> In code/index.html
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507628036>
> :
>
> > +    <section class id="weather-wrap">
>
> +      <h1>Toronto Forecast</h1>
>
> +    </section>
>
> +
>
> +    <section class="main">
>
> +      <img class="cn-img" src="./assets/cntower.png" height="100px" />
>
> +      <div class id="city">
>
> +        <p>Toronto, ON</p>
>
> +      </div>
>
> +      <div class id="date"></div>
>
> +      <p>Current temperature:</p>
>
> +      <div class id="temperature"></div>
>
> +      <p>Visibility:</p>
>
> +      <div class id="description"></div>
>
> +      <img id="visibilityIcon" style="width: 40px" src="" />
>
> +      <div class="highLow">
>
>
> classes should be written in kebab-case, not camelCase
> ------------------------------
>
> In code/index.html
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507628393>
> :
>
> > +      <p>Current temperature:</p>
>
> +      <div class id="temperature"></div>
>
> +      <p>Visibility:</p>
>
> +      <div class id="description"></div>
>
> +      <img id="visibilityIcon" style="width: 40px" src="" />
>
> +      <div class="highLow">
>
> +        <p>H:</p>
>
> +        <div class id="H"></div>
>
> +        <p>L:</p>
>
> +        <div id="L"></div>
>
> +      </div>
>
> +
>
> +      <p>Feels Like:</p>
>
> +      <div class id="feelsLike"></div>
>
> +      <section class id="sunUpSunDown">
>
> +        <p>Sunrise: <img src="./assets/sunrise.png" style="width: 20px" /></p>
>
>
> Width of an image should be defined in CSS, not in HTML
> ------------------------------
>
> In code/style.css
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507628581>
> :
>
> > +@import url("https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap");
>
> +
>
> +* {
>
> +  margin: 0;
>
> +  padding: 0;
>
> +  box-sizing: border-box;
>
> +}
>
> +
>
> +body {
>
> +  font-family: "Roboto Mono", monospace;
>
> +}
>
> +
>
> +h1 {
>
> +  text-align: center;
>
> +  font-size: 20px;
>
> +  margin: 50px 50px;
>
>
> margin: 50px is shorthand
> ------------------------------
>
> In code/style.css
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507628829>
> :
>
> > +  padding: 5px;
>
> +}
>
> +
>
> +.main {
>
> +  background-color: rgba(255, 255, 255, 0.219);
>
> +  border: 2px solid rgba(255, 250, 250, 0.329);
>
> +  border-radius: 20px;
>
> +  align-items: center;
>
> +  text-align: center;
>
> +  width: 100%;
>
> +  margin: auto;
>
> +  padding: 20px;
>
> +  font-size: 14px;
>
> +}
>
> +
>
> +#temperature {
>
>
> We shouldn't style by id's at all, always use classes
> ------------------------------
>
> In code/style.css
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507633330>
> :
>
> > +
>
> +.forecast-h1 {
>
> +  color: rgb(199, 125, 125);
>
> +  font-size: 18px;
>
> +  margin: 0;
>
> +}
>
> +
>
> +.column {
>
> +  display: flex;
>
> +  flex-basis: 40%;
>
> +  margin: auto;
>
> +}
>
> +
>
> +/* CHANGING BACKGROUND BASED ON TEMP*/
>
> +body.cold {
>
> +  background-image: url(./assets/cold.jpg);
>
>
> It's more safe to wrap url around quotes - some browsers might have
> problem with reading path without them
>
> background-image: url("./assets/cold.jpg");
>
>
> ------------------------------
>
> In code/weather.js
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507634026>
> :
>
> > +    } if (weather == 'Snow') {
>
> +        document.getElementById('visibilityIcon').src = 'assets/snow.png'
>
> +    } if (weather == 'Hail') {
>
> +        document.getElementById('visibilityIcon').src = 'assets/hail.png'
>
> +    } if (weather == 'Thunder') {
>
> +        document.getElementById('visibilityIcon').src = 'assets/thunder.png'
>
> +    } if (weather == 'Haze') {
>
> +        document.getElementById('visibilityIcon').src = 'assets/thunder.png'
>
> +    }
>
> +}
>
> +//CHANGING BACKGROUND DEPENDING ON TEMP
>
> +const changeBackground = (json) => {
>
> +    if (json.main.temp.toFixed(0.5) <= 10 || json.main.feels_like.toFixed(0.5) <= 10) {
>
> +        body.classList.add('cold')
>
> +    } else if (json.main.temp.toFixed(0.5) >= 22 || json.main.feels_like.toFixed(0.5) >= 2) {
>
> +
>
>
> empty line
> ------------------------------
>
> In code/weather.js
> <https://github.com/Technigo/project-weather-app/pull/137#discussion_r507634826>
> :
>
> > +            }
>
> +        }
>
> +    })
>
> +    const forecast = document.getElementById('weatherForecast')
>
> +    const forecastIcon = document.getElementById('forecastIcon')
>
> +    forecast.innerHTML = ""
>
> +    for (const date in minMaxTemps) {
>
> +        const forecast = document.getElementById('weatherForecast')
>
> +        forecast.innerHTML += `<div class="column">${minMaxTemps[date].dayOfWeek}</div>`
>
> +        forecast.innerHTML += `<div class="column">${minMaxTemps[date].minTemp.toFixed(0.5)} °C|${minMaxTemps[date].maxTemp.toFixed(0.5)} °C </div>`
>
> +        forecast.innerHTML += `<img src="http://openweathermap.org/img/wn/${minMaxTemps[date].icon}@2x.png"></img>`
>
> +    }
>
> +}
>
> +// Fetch 5 day Forecast Data
>
> +fetch(weatherForecastUrl)
>
> +    .then((response) => { return response.json() })
>
>
> You don't need to write return keyword and brackets if it's same line :
>
> .then(response => response.json())
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-weather-app/pull/137#pullrequestreview-511607310>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALXMX2WQO33KKJLWUNLEPHTSLQHUHANCNFSM4R3YGU7A>
> .
>

2020-12-04 16:33 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging