Agnes weather app
Technigo/project-weather-app pull request #138
Opened 2020-09-27 20:30 UTC by aagneshansson

Link to my deployed project:
https://agnesweatherapp.netlify.app/

My reflections on how this week's project turned out:
The most fun project so far during this bootcamp. 

Things I'd like to have clarified or explained in more detail:
Map and more examples how to use it in relation to other functions.

2020-10-04 13:54 UTC, petrame reviewed
Lovely weather app with some cool animations and styling, I really like the idea with a landing page. A fav-icon had been the icing on the cake :)

It was interesting to check out your code since you did some features that I didn't have time for. The way of doing the hamburger menu was new to me.

Your code is well structured with easy-to-understand-comments. I wonder if there is a way to avoid duplication of code when you have multiple htlm and javascript files, but that's maybe something for the real code coaches to comment on.

Remember to remove your console logs when you are done.

2020-10-04 13:54 UTC, petrame commented on code/index.html
> +  </main>
There is no `<main>` starting tag.

2020-10-04 13:54 UTC, petrame commented on code/lysekil.html
> +    </div>
I think there is two more `</div>` than it should be.

2020-10-04 13:54 UTC, petrame commented on code/style.css
> +    }
Nice structured css file. Comments and logic names makes it easy to read.

2020-10-04 13:54 UTC, petrame commented on README.md
> +As I found this as a very fun and challenging project, I decided to try to achieve black level. I used two different api's to fetch the weather for Lysekil, my home town. Additionally I used if/else
I think it's great that you decided in advance what you would spend your time on. It's easy to get caught up in the styling. And your page still looks really nice :)

2020-10-04 13:54 UTC, petrame commented on code/geo.js
> +    if (temp > 30.0) {
I believe it's good practice to declare functions with const even if it obviously works without.

2020-10-04 13:54 UTC, petrame commented on code/geo.js
> +};
Nice feature with different color depending on temperature.

2020-10-04 13:54 UTC, petrame commented on code/script.js
> +menuBtn.addEventListener("click", toggleMenu);
Line 12 and 15 is duplicates.

2020-10-04 13:54 UTC, petrame commented on code/style.css
> +
Great way of commenting!

2020-10-04 13:54 UTC, petrame commented on code/style.css
> +
Love the rotation animation and the fold out menu.

2020-10-04 13:58 UTC, petrame approved these changes
Forgot to change status of the PR.

2020-10-19 10:46 UTC, EmOlsz requested changes
It's pretty impressive code, I have to say that Agnes! A lot of extra requirements done :)
However, with such complexity you didn't avoid many mistakes. Your code is a bit chaotic and has a lot of small mistakes. Please, take a look on both Petra's and my comments and provide changes

2020-10-19 10:46 UTC, EmOlsz commented on code/geo.html
> +        </li>
Yep, probably some typo

2020-10-19 10:46 UTC, EmOlsz commented on code/geo.html
> +    <div class="todaysGeo" id="todaysGeo"></div>
classes should be written in `kebab-case`, not `camelCase`

2020-10-19 10:46 UTC, EmOlsz commented on code/geo.js
> +            let sunrise = (new Date(todaysgeo.sys.sunrise * 1000).toLocaleTimeString("en-US", { timeStyle: "short" }));
No need to wrap everything in parentheses.
Moreover, I can't see any place where you are overwriting value of `sunrise` variable, so it should be declared with `const`

2020-10-19 10:46 UTC, EmOlsz commented on code/geo.js
> +            console.log(filteredGeoForecast);
Delete all console.logs before pushing your code to GitHub

2020-10-19 10:46 UTC, EmOlsz commented on code/style.css
> +  background: url(background.jpg);
It's far more safe to use quotes around url, some browsers might have problem with reading path without them :

```
background: url("background.jpg");
```

2020-10-19 10:46 UTC, EmOlsz commented on code/style.css
> +#home {
We shouldn't style by id's

2020-10-19 10:46 UTC, EmOlsz commented on code/style.css
> +  padding-top: 0px;
`padding-top: 0;`

2020-10-19 10:46 UTC, EmOlsz commented on code/style.css
> +  @media (min-width: 1025px) {
You started to nest one `@media` inside another because you forgot about closing bracket in line 206

2021-01-05 10:11 UTC, EmOlsz commented
Thank you for your changes Agnes!
Still waiting for the last change https://github.com/Technigo/project-weather-app/pull/138#discussion_r507640037
After fixing this issue, I will approve your project!

2021-02-17 09:05 UTC, aagneshansson commented on code/geo.js
> +            let sunrise = (new Date(todaysgeo.sys.sunrise * 1000).toLocaleTimeString("en-US", { timeStyle: "short" }));
Implemented 😄

2021-02-17 16:35 UTC, EmOlsz approved these changes

2021-02-18 11:57 UTC, closed without merging