Axel's weather app submission
Technigo/project-weather-app pull request #143
Opened 2020-09-27 22:53 UTC by AxelHammarback

**Link to my deployed project:**
http://axel-weather.netlify.app/

**My reflections on how this week's project turned out:**
I'm very happy with my work and how the way this week's project turned out. It a struggle initially, but when I understood the fetch concepts and how to work with the data, it became incredibly fun. Also, CSS is hard.

**Things I'd like to have clarified or explained in more detail:**
I still struggle with looping through the contents of an object. Is that possible?

2020-09-28 12:37 UTC, VanessaSue27 approved these changes
Hello hello!
I learned so much by reviewing your code, Axel! 😎

I can tell you do a lot of research and try to implement new methods, nice to see that interest to find new tools!
I have also noticed the eye for detail and design here: there are so many small effects carefully chosen and implemented, I'm very impressed by that. Especially the header section with the hover effects on buttons.
I admire that you implemented this City Selector input, it could not have been so simple and the result is great!
As I mentioned above, all the color changes, hover effects, and ALSO the animation on the weather icon, makes this weather app stand out. I loved discovering all those small details 🤩

I also had a good laugh reading through the commit messages 😝 It was like reading a funny journal, and I can agree: CSS - the struggle is real! 💪

I noticed the .gitignore file missing - nice to add it so you avoid the DS_Store files.

I will need some help from the coach later on regarding the SVG jQuery file: I heard from some team mates that they were struggling to get the icons to work because they were in SVG format - so I'm assuming this was your way to work around it? But since I have no knowledge on jQuery, not sure which feedback to give here~~

All in all a really interesting project to review, and I am glad you took the time to understand and make fetch() work 💪 It was a process for all of us, but now we can see the great results! 💥

I have left a lot of comments, but I don't find anything crucial that needs to be changed (regarding indentation and variable namig and so on), so I'm going to mark it as Approved and wait for the coach to get back to us 😁

My pleasure reviewing your code,
Vanessa ~~

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  display: flex;
The body is set to `display: flex`
This doesn't seem to have any effect when I tested it on dev tools.
Maybe this line could be removed?

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  margin: auto;
This container is set to have a width of 100%, so `margin: auto` doesn't seem to have any effect
Maybe it can be ommitted?

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  position: relative;
Super good that you use position in your project - I shy away from using most of the time 🙈

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  position: fixed;
This one container has two position rules: one set to relative and one set to fixed (It seems fixed is the one being ignored, so maybe it can be removed?)

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  align-items: center;
This one is being set to `display: flex` but no direction is specified, so `align-items: center;` doesn't seem to be having any effect, maybe it's not necessary to have that line?

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +.button-primary:focus {
Unsure about the difference between hover and focus in this case (I will need some extra insight help here)
But they both have the same properties: 
```
background-color: white;
 border: 4px solid #0C60F2;
```
Can we avoid having to declare them twice? (same for lines 135-140)

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  box-sizing: border-box;
Okay, one of the only times I see border-box being used effectively. I was not really clear why I would use border-box, but I think seeing your buttons and the effect you have created using this property, I understand what can be achieved with it 🤩 NICE!

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  animation: MoveUpDown 4s ease-in-out infinite;
Animation, yessss!!! 💥

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  flex-direction: row;
Here this `flex-direction` doesn't seem to be having an effect, can it be avoided?

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +/* I left the "border: 1px dashed" lines due to debugging purposes. */
Really good tip! I also use these borders when styling to know what is going on with each element 👌

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  vertical-align: top;
`vertical-align` being declared twice here, when testing it I found `vertical-align: super` is the one being ommitted, so maybe that one can be removed

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +/* "The one key thing to remember when trying to position a child div relative to it’s parent is that the child should be given the CSS property position:absolute; and the parent set to either positi
AMAZING reminder! 🎉

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +  position: absolute;  right: -20px;
`right: -20px`
can start in the next line instead

2020-09-28 12:37 UTC, VanessaSue27 commented on code/style.css
> +.image-hero-weather-container {
The styling for `image-hero-weather-container` is already declared on line 193.
I couldn't find anything particular, but is there a reason why it needs to be delcared here again? Nothing in the styling seems to have changed from the original declaration~

2020-09-28 16:50 UTC, AxelHammarback commented on code/index.html
> +  <script src="svgColor.js" defer></script>
Ah yes, need to remember to add the dot. Thanks, Vanessa!

And in this case, it's (probably) not needed since they're in the bottom of the HTML, but I just try to make it a habit to add "defer". (If a code coach reading this can think of a reason not to, feel free to comment here.)

2020-09-28 16:52 UTC, AxelHammarback commented on code/script.js
> +const fetchWeatherImage = (weather) => {
initially they were added for debugging purposes – but later on, I thought "Hmm, maybe I should print a nicer-looking message to the DOM". I ended up not printing them in the DOM, but left them if I want to revisit this some day

2020-09-28 16:52 UTC, AxelHammarback commented on code/style.css
> +  vertical-align: top;
Awesome, good find – thanks!

2020-09-28 16:54 UTC, AxelHammarback commented on code/style.css
> +/* "The one key thing to remember when trying to position a child div relative to it’s parent is that the child should be given the CSS property position:absolute; and the parent set to either positi
Ah, yes – found it here: https://tomelliott.com/html-css/css-position-child-div-parent

But left it as a comment to try to remember it better :D

2020-09-28 16:55 UTC, AxelHammarback commented on code/style.css
> +.image-hero-weather-container {
Nope, I just missed it due to sloppiness 😅

2020-10-19 14:58 UTC, EmOlsz requested changes
Well done, solid project Axel! I like your solutions to our requirements, you've done a lot of extra stuff :)
There are some things I would like you to fix, please, take a look on my comments and provide changes.
Apart from that, really nice job!

2020-10-19 14:58 UTC, EmOlsz commented on README.md
> +
Indeed :)

2020-10-19 14:58 UTC, EmOlsz commented on code/countryTransform.js
> +var isoCountries = {
Very ambitious Axel, well done solid job!

2020-10-19 14:58 UTC, EmOlsz commented on code/index.html
> +  <link rel="stylesheet" href="style.css">
`./`

2020-10-19 14:58 UTC, EmOlsz commented on code/index.html
> +
A lot of empty lines, let's delete them. For the future - one empty line between elements in considered maximum

2020-10-19 14:58 UTC, EmOlsz commented on code/index.html
> +  <script src="svgColor.js" defer></script>
Well, since you add your scripts at the end of HTML, there is no need to add defer from logical point of view, but it's no harm that you added them anyway ;)

2020-10-19 14:58 UTC, EmOlsz commented on code/index_backup.html
> +  <link rel="stylesheet" href="style.css">
`./`

2020-10-19 14:58 UTC, EmOlsz commented on code/index_backup.html
> +  <!-- <script src="svgColor.js" defer></script> -->
Before final push, always remember to delete all commented code

2020-10-19 14:58 UTC, EmOlsz commented on code/response.js
> +// Fields in API response
Hmm, I don't think you need this file ;)

2020-10-19 14:58 UTC, EmOlsz commented on code/script.js
> +  var inputCity = document.getElementById("inputCity")
Yes, definitely!

2020-10-19 14:58 UTC, EmOlsz commented on code/script.js
> +    console.log("It's cloudy today.");
A lot of console.logs - we should delete all of them before final push

2020-10-19 14:58 UTC, EmOlsz commented on code/style.css
> +  margin: auto;
Depends if this `margin: auto` is used later on in different resolutions

2020-10-19 14:58 UTC, EmOlsz commented on code/style.css
> +  top: 0;
Proper order - top, right, bottom, left

2020-10-19 14:58 UTC, EmOlsz commented on code/style.css
> +
A lot of empty lines

2020-10-19 14:58 UTC, EmOlsz commented on code/style.css
> +  padding: 0px;
`padding: 0;`

2020-10-19 14:58 UTC, EmOlsz commented on code/style.css
> +  background-image: url(./assets/clouds-top-border.svg);
It's safer to wrap url in quotes, some browsers might have problem with reading path without them :

```
background-image: url("./assets/clouds-top-border.svg");
```

2020-10-19 14:58 UTC, EmOlsz commented on code/svgColor.js
> +// Source: https://stackoverflow.com/questions/11978995/how-to-change-color-of-svg-image-using-css-jquery-svg-image-replacement
Good job with outer library!

2020-12-13 20:04 UTC, AxelHammarback commented
Hey @EmOlsz! Sorry for the very late fix. Really good comments, I agree with them all and changed the app according to the review. Take care, see you tomorrow 👋

2020-12-14 16:11 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging