Week 6
Technigo/project-weather-app pull request #145
Opened 2020-09-28 09:13 UTC by ckjerrgren

https://youthful-kilby-c391cd.netlify.app

**My reflections on how this week's project turned out:**
It took me FOREVER to do the 5 day forecast, and I still feel like I don't quite understand how it works. 
Related to that I didn't put much effort in to styling due to lack of time. I wish it looked better but i'm knackered. 

**Things I'd like to have clarified or explained in more detail:**
Oh everything haha

2020-09-30 16:37 UTC, annahasselstrom approved these changes
I can so relate Claudia! It is not easy to wrap one's head around this. Although you say you didn't spend much time on styling, your styling feels very balanced ⭐️.  There are some empty lines here and there that you can get rid of. But perhaps the most important thing (?) to look at is how to make your five-day-forecast less repetitive by using .forEach or .map. But having said that, when it comes to functionality, the blue level requirements are there (I think) - well done!

2020-09-30 16:37 UTC, annahasselstrom commented on code/index.html
> +    <!-- Glöm inte meta-tag & favicon  -->
Should there by two meta tags here? Or could they be put into one? Did you forget the favicon? ☺️

2020-09-30 16:37 UTC, annahasselstrom commented on code/index.html
> +    </header>
Should these be on two different lines?

2020-09-30 16:37 UTC, annahasselstrom commented on code/index.html
> +
Perhaps delete one empty line?

2020-09-30 16:37 UTC, annahasselstrom commented on code/index.html
> +    <!-- Five day forecast-->
Nice that you comment your code! Make it easier for me to follow the structure.

2020-09-30 16:37 UTC, annahasselstrom commented on code/main.css
> +height: 30px;
This should be indented?

2020-09-30 16:37 UTC, annahasselstrom commented on code/main.css
> +
There are some formatting that could be cleaned up. Mainly some empty lines here and there. Apart from that - easy to read 🙌

2020-09-30 16:37 UTC, annahasselstrom commented on code/script.js
> +//fetch - "stop trying to make fetch happen ;)" KOLLA HUR DETTA SKA VARA INDENTERAT
I think the indentation is correct. Perhaps remove empty lines though?

2020-09-30 16:37 UTC, annahasselstrom commented on code/script.js
> +
Your code below looks very neat 🤩  but  there is some repetition going on - instead of having to perform each line of code for each day, you should be able to use a .forEach() method or .map() to get to the same result but with less lines of code?

2020-09-30 16:37 UTC, annahasselstrom commented on code/script.js
> +
A few empty lines to delete.

2020-10-20 06:07 UTC, EmOlsz requested changes
In general it's good project Claudia, congrats :) Nonetheless, there is some stuff that you need to fix.
As far as I can see, you haven't get rid of bad habits in code (uppercase class names, lack of consistency about semicolons, commented code). We are slowly entering advanced JavaScript - because of that we have to have our habits fixed and straight. Please, take a look on my comments and provide changes.
Apart from that - good job :)

2020-10-20 06:07 UTC, EmOlsz commented on code/main.css
> +height: 30px;
Yep

2020-10-20 06:07 UTC, EmOlsz commented on code/main.css
> +
Unnecessary empty line

2020-10-20 06:07 UTC, EmOlsz commented on code/main.css
> +
1. Commented code should be deleted before final push
2. There are no styles for responsiveness

2020-10-20 06:07 UTC, EmOlsz commented on code/script.js
> +    let readableTime = new Date(timestamp * 1000);
Sometimes you use semicolons and sometimes you don't - we have to be consequent about that

2020-10-20 06:07 UTC, EmOlsz commented on code/script.js
> +})
Wrong indentation

2021-02-18 22:59 UTC, ckjerrgren commented
Added quick responsiveness and cleaned up code

2021-02-19 08:33 UTC, EmOlsz approved these changes

2021-03-11 09:14 UTC, closed without merging