Week 6 - Weather app, blue level - Nadia Mazzoni
Technigo/project-weather-app pull request #149
Opened 2020-09-28 22:39 UTC by Bluepoisson

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-09-30 15:41 UTC, bloeli requested changes
Nice that you are stubborn and make progress even though I think you have felt a bit frustrated, at least I do when I wan't to understand and make it on my own/are stubborn and things maybe don't go as fast and doesn't work the way I would like it. But I guess not giving up, and ask for help (kastrull as you said today haha) is important and I think you have a great spirit beeing stubborn and also not giving up, but don't forget about the kastrull :) I feel a lot frustrated understanding Javascript, even though I made a weather app that works kind of well, I can feel that I now does'nt really know what I've done everywhere. I google a lot, ask for help sometimes, and also check other peoples code, try implement what I found, understand it and also test/play around. Then I aim for doing some practice and learn Javascript at codeacademy and w3schools, and hope it will make more sense a long the way. Maybe this wasn't the greatest code review since I struggle my self with Javascript, and cannot give you tips on how to solve things, but I hope and belive you will solve this, asking for help,, looking at other peoples code/projects and help from code coachers :) <3

2020-09-30 15:41 UTC, bloeli commented on index.html
> +    <title>Weather 2GO</title>
Nice name!

2020-09-30 15:41 UTC, bloeli commented on README.md
> +Learning how to fetch an api and displaying wanted data was quite simple until I encountered an array and had to format time and dates. My knowledge was base being far too slim combined with my stubb
Agree, I googled some and found a solution finally

2020-10-20 06:37 UTC, EmOlsz approved these changes
Good job in general Nadia :) You've met basic requirements.
Please, take a look on my comments, hope they will help you improve!

2020-10-20 06:37 UTC, EmOlsz commented on index.html
> +    <link rel="stylesheet" href="style.css" />
Let's not forget about `./` in path to file

2020-10-20 06:37 UTC, EmOlsz commented on script.js
> +
Let's delete those empty lines

2020-10-20 06:37 UTC, EmOlsz commented on script.js
> +  .then(weatherToday => {
Nope, since it's one argument we don't need to wrap it in extra parentheses

2020-10-20 06:37 UTC, EmOlsz commented on script.js
> +
Once again, too much empty lines. One is completely enough

2020-10-20 06:37 UTC, EmOlsz commented on script.js
> +
Aaand over here ;)

2020-10-20 06:37 UTC, EmOlsz commented on style.css
> +#container {
We should avoid styling by id's and stick only to classes

2020-10-20 06:37 UTC, EmOlsz commented on style.css
> +  background-image: url(./images/parasol.png);
It's more safe to wrap url in quotes, some browsers might have problem with understanding path without them :

```
background-image: url("./images/parasol.png");
```

2020-10-20 06:37 UTC, EmOlsz commented on style.css
> +  margin-top: -300px;
It's almost always possible to use different approach than negative margins - maybe opposite margin on different element above?

2021-02-16 17:53 UTC, closed without merging