Pull request weather app
Technigo/project-weather-app pull request #152
Opened 2021-02-19 12:19 UTC by Sartish

Link to my deployed project: https://inspiring-archimedes-330d55.netlify.app/

My reflections on how this week's project turned out:
- Really great to work in pairs for this, since it involved a lot of JS 
- css harder than expected, due to adding html in JS so difficult to style
- learned a lot and happy with result 

Things I'd like to have clarified or explained in more detail:
-Perhaps responsiveness and more css provided from the beginning would be great :)

2021-02-24 10:30 UTC, Bellsibub requested changes
OMG! This site is soooooo beautiful 💕!!
Your code was very impressive and minimal in regards to the amount stuff that is happening on the site 🎉 

### Changes Requested
There were only a few formatting issues found in this project. No functional bugs that I encountered 👍 
But regarding the formatting issues, you can find them individually marked as comments below.

> Changes requested are marked with a ❗ at the start of each comment below, so you can easily find them

### Other Comments
Moreover there are other comments not marked with an exclamation. Those are either some general suggestions OR just parts I **_really really_** liked. You should both be very proud of this project and what you achieved. 🙌

2021-02-24 10:30 UTC, Bellsibub commented on style.css
> +    /* background: linear-gradient( 0deg, rgb(170, 189, 132) 0%, rgb(208, 194, 163) 72% ); */
Remember to remove any comments from development 😉

2021-02-24 10:30 UTC, Bellsibub commented on style.css
> +    grid-template-columns: 1fr 1fr 1fr;
😃 Awesome use of css-grid  💯

2021-02-24 10:30 UTC, Bellsibub commented on style.css
> +#all-days{
❗ **Formatting issue:**
We should avoid styling using id selectors.
**Suggested change**: add a class to this element and use that instead. Id's should only be primarily in the javascript file. 
> This issue applies to the following lines: 68, 119 and 135

2021-02-24 10:30 UTC, Bellsibub commented on script.js
> +            }
❤️ Love this solution! 😄

2021-02-24 10:30 UTC, Bellsibub commented on script.js
> +        //Adds a 0 to the hour and minutes if less than 10
Just in general great use of comments to describe the actions happening in the function through out this entire file 💯 😄

2021-02-24 10:30 UTC, Bellsibub commented on style.css
> +}
🥳 This design is just....just great!! 😍 The use of linear-gradient in conjunction with the beautiful image is just top-notch. And the layout of this element is probably my favorite part 😁

2021-02-25 13:20 UTC, KarolCislowski approved these changes
This is a very nice and clean project 🌈 
These icons make a very visual effect. 🦄 

You asked about responsive design. I can see that you understand it well. Styling is not math unfortunately and knowledge is a very small factor of how good you are with it. You need to practice it to master it 🎨 

Please let me know who was in a team with you 😸

2021-02-25 13:20 UTC, KarolCislowski commented on style.css
> +}
You shouldn't use ids for styling purposes 🎨

2021-03-07 11:12 UTC, Sartish commented on style.css
> +    height: 100%;
thanks Bella, We had so many issues with this, back  and changed back and forth between 100% and 100vh, but will change again to 100vh and hope it will work ⭐️

2021-03-07 11:46 UTC, Sartish commented on style.css
> +    height: 100%;
Actually when changing to 100vh, the site looks strange for me in my browser with white border. So we had to change back 100% and see if we find another solution.

2021-03-07 11:48 UTC, Sartish commented on index.html
> +            <div id="weather-container__info">
Fixed ->  Sari, you can resolve conversation

2021-03-07 11:51 UTC, Sartish commented on index.html
> +            <div id="all-days"></div>
Now changed, Sari you can resolve conversation when you seen this

2021-03-07 11:53 UTC, Sartish commented on style.css
> +#all-days{
Now changed, added class instead. Sari you can resolve conversation when viewed this comment

2021-03-07 11:59 UTC, Sartish commented on style.css
> +}
Class added for css purporses (.city) Sari you can resolve when seen comment

2021-03-07 15:03 UTC, sarianne-peltola commented on style.css
> +    height: 100%;
Yes for me it looks now strange in developer tool (and 100vh fixes it), but it looks fine in my phone and browser with 100% too.

2021-09-07 08:47 UTC, closed without merging