Weather app by Ann-Sofi Jönsson & Astrid Persson
Technigo/project-weather-app pull request #154
Opened 2021-02-19 13:51 UTC by Ann-Sofi

Link to my deployed project:
https://sad-snyder-d2fc68.netlify.app/

Things I'd like to have clarified or explained in more detail:
1. We have a lot of "let". How can we determine of when it's good to use const? Can we change any of our let to const?
2. When viewed on iphone the time has seconds..but not on android. why?
3. When viewed on my samsung, the icons doesn't show.. There are some browser issues? But how do we fix it?

2021-02-24 17:39 UTC, darcywinterhill approved these changes
Good job !
Not only with the main functions but also finding solutions for things that didn't work on iOS.

2021-02-24 17:39 UTC, darcywinterhill commented on code/app.js
> +    let sunset = new Date(sunsetAPI*1000).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'});
Like you said! A lot of let's 😸
Since you don't change the value in them in your code they can be consts.

2021-02-24 17:39 UTC, darcywinterhill commented on code/app.js
> +    let tempTodayRounded = Math.round(tempToday)
The brief had the instructions to "present the data: the city name, the temperature (**rounded to 1 decimal place**)". In your code you round up to an integer.

2021-02-24 17:39 UTC, darcywinterhill commented on code/app.js
> +}
Great job with this solution!

2021-02-24 17:39 UTC, darcywinterhill commented on code/style.css
> +  }
Would have been fun to see something more responsive happening when viewing it on tablet or desktop! 🤗

2021-02-24 17:39 UTC, darcywinterhill commented on README.md
> +We noticed that after we had done the filter to get the 12.00 weather for 5 days, we couldn't use the same line of codes to fetch the same information that we got on today's weather.
Great spotted!

2021-02-24 17:39 UTC, darcywinterhill commented on code/index.html
> +      Loading...
Smart with the Loading text!

2021-02-25 13:41 UTC, KarolCislowski commented on code/app.js
> +    let sunset = new Date(sunsetAPI*1000).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'});
The rule is to create always `consts` and change it to let when the compiler is whining something like "you are trying to change the const..." 🗡️ later in the react world you will see let less often than 🦄 in Swedish forests.

2021-02-25 13:55 UTC, KarolCislowski requested changes
You created a very nice app but I need to ask you to make it more responsive to meet the blue level requirements.

2021-02-25 13:55 UTC, KarolCislowski commented on code/style.css
> +  }
This is not a responsive app. It is not scaling up properly. even on bigger phones like Samsung Note 20 user can see the white margin and it is not desired.

2021-09-07 08:25 UTC, closed without merging