Weather App
Technigo/project-weather-app pull request #156
Opened 2021-02-19 14:33 UTC by leelalaim

Link to my deployed project: https://weather-in-stockholm-forecast.netlify.app/
Made by: Laima and Hannah (Lion team)

2021-02-24 12:55 UTC, sssylvasss reviewed
Really nice weather app with a lot of features, such as icons changing depending on weather, background images that change depending on weather, and forecast that expands in iPad version. Styling looks very nice with custom fonts.
The blue level is reached (except a responsive version for desktop is lacking).
Part of red level is reached, for example different background images depending on weather.
Generally the code is easy to understand and well organized and commented in a clear way (especially for the js-file). Good intention. The styling is nice, you added new fonts, icons and background images. 

Great job!

2021-02-24 12:55 UTC, sssylvasss commented on code/index.html
> +
HTML
Good intention, well structured and easy to understand. 
Mixing single and double quotes.
Maybe semantic tags such as section could be used instead of some divs?

2021-02-24 12:55 UTC, sssylvasss commented on code/index.js
> +        console.log(shortForecastDescriptions)
Remove console.log

2021-02-24 12:55 UTC, sssylvasss commented on code/index.js
> +        console.log(longFcstDescriptions)
Remove console.log

2021-02-24 12:55 UTC, sssylvasss commented on code/index.js
> +        console.log(dayOfWeek)
Remove console.log

2021-02-24 12:55 UTC, sssylvasss commented on code/index.js
> +
JS
Really clean and well organized code with a clear logic and easy to follow. A lot of commenting makes the code easy to understand.

2021-02-24 12:55 UTC, sssylvasss commented on code/style.css
> +        /*height: 1024px;*/
Remove unused code

2021-02-24 12:55 UTC, sssylvasss commented on code/style.css
> +        justify-content:center;
add space before "center"

2021-02-24 12:55 UTC, sssylvasss commented on code/style.css
> +    color: #fff;
Maybe better to add the color to the .body for less code?

2021-02-24 12:55 UTC, sssylvasss commented on code/style.css
> +}
The order here isn’t as well organized and clear as in the other documents. It’s a little bit harder to understand and follow the code. Maybe it would be easier if the order was the same as in the html, going from top to bottom? Now you start with the h1/h2/h3 etc.
You also mix using classes and h1/h2/h3 for text styling. Maybe all text could be styled by classes to make it easier to understand?
No design for desktop version in media queries.

2021-02-25 14:22 UTC, KarolCislowski requested changes
This a very nice project 🌈  but to meet the blue level's requirements you need to manage to have all  5 days in your forecast on every screen size. It is important to learn how to provide a responsive design without losing functionalities 🎨

2021-02-26 08:58 UTC, leelalaim commented
Made the requested changes. Commented out the 3-day forecast (as we would like to keep this feature in our project for future), to meet the blue level requirements.

2021-03-04 05:26 UTC, KarolCislowski approved these changes
Great Job 🦄

2021-09-07 08:25 UTC, closed without merging