Project week 6/Atefeh-Ulysses-Nazanin
Technigo/project-weather-app pull request #159
Opened 2021-02-19 17:29 UTC by nazi-pira

Link to my deployed project:
https://priceless-chandrasekhar-e94c89.netlify.app/

My reflections on how this week's project turned out:
This week's project has cheered us up by how we can make a practical application after just six week in the bootcamp! We have faced problems regarding the Date and the min & max temperature but has managed to figure a solution out by some googling.

2021-02-23 15:57 UTC, Ingetora reviewed
Nice job! Functional app, we would use it! 

// Vlad and Maria

2021-02-23 15:57 UTC, Ingetora commented on index.html
> +    <meta name="viewport" content="width=width-device, initial-scale=1.0">
We get an warning in console for width-device. But it seems it's not affecting the app.

2021-02-23 15:57 UTC, Ingetora commented on script.js
> +
Very nice, clean code. Easy to understand. App is fully functional and straight forward to use. Hamburger menu doesn't seem to have a function, and should mabye be removed.

2021-02-25 15:18 UTC, KarolCislowski requested changes
Your app has very nice logic and functionality 🦄 
You need to however work on styling a little more. Responsiveness is not to create a cut-out small area from the background, but make your app look good on every screen. 
You are very close to meet the requirements for this project! 🦾

2021-05-19 15:50 UTC, nazi-pira commented
> Your app has very nice logic and functionality 🦄
> You need to however work on styling a little more. Responsiveness is not to create a cut-out small area from the background, but make your app look good on every screen.
> You are very close to meet the requirements for this project! 🦾

Thank you so much for the nice comments! we would be appreciated if you enlighten us with a hint or a suggestion of the needed changes.

2021-05-22 09:20 UTC, KarolCislowski approved these changes

2021-09-07 08:25 UTC, closed without merging