Weather app by Maidelin R. and Mette W.
Technigo/project-weather-app pull request #162
Opened 2021-02-20 09:09 UTC by ettem

Link to our deployed project:
https://silly-mayer-9c5b17.netlify.app/

Reflections on how this week's project turned out:
We are very proud of what we’ve accomplished this week. It has been a though week for both of us personally but we still managed to do some stretch goals for our project and for that we are happy!

2021-02-24 09:44 UTC, klimenko3007 commented
Dear Mette and Maidelin, we think your project looks really amazing. We really liked your icons (so much better than those you can fetch with API), very nice colour solutions and use of gradient. We also really liked your animations. The code looks very clean, very clear code description, very good documentation. 
We only noticed one problem: times of sunset and sunrise do not seem to be correct for different time zones (Moscow and Rome). We have some comments in the code section in the github that are just our suggestion for your consideration rather than require a change.

2021-02-24 10:03 UTC, klimenko3007 requested changes
Great job!! We really liked it!!

2021-02-24 10:03 UTC, klimenko3007 commented on code/index.html
> +      <ul id="cities-popup-list" class="cities-popup-list">
It is really cool solution with buttons and the choice of several cities. The only suggestion we have is to add pointer cursor to your page, so that users can understand that they can click on the city to see more cities options. In SCC you can use "cities-popup-list" class and add
.cities-popup-list{
 cursor: pointer;
}

2021-02-25 16:08 UTC, KarolCislowski approved these changes
This is a very impressive project! 🌈 It works nice and if you change the time-zone and min-max temperature issues it will be perfect 🦄 

I like your styling very much! 
Great job!

2021-02-25 16:08 UTC, KarolCislowski commented on code/weather.js
> +                    <h3>${Math.round(forecastDay.main.temp_max)}°C</h3>
min and max are the same in your app 🐛 🐞 ... you need to find out why  😸

2021-09-07 08:25 UTC, closed without merging