Week 6 - Weather App
Technigo/project-weather-app pull request #170
Opened 2021-02-21 09:03 UTC by rrpersson

Group project with me and Pauline Andersson.

My Repo:
https://github.com/rrpersson/project-weather-app

Live Website:
https://reverent-hamilton-99ea7e.netlify.app/

2021-02-24 19:02 UTC, CarolineF3 commented on code/index.html
> +  </nav>
<nav> tags should only contain navigation elements.

alt=""  is empty, perhaps they should be erased?

2021-02-24 19:07 UTC, CarolineF3 commented on code/weather.js
> +  fetchWeatherForecast(API_urlForecast)
Missing semicolon :)

2021-02-24 19:36 UTC, CarolineF3 commented on code/style.css
> +}
It's great that you added comments! Since the file consists of so many lines, adding some headlines might be a good idea.

2021-02-24 19:52 UTC, CarolineF3 commented on code/weather.js
> +})
Great job! It's good that you have a lot of small functions. :) The comments are really nice as well, the code is easy to comprehend.

2021-02-24 20:08 UTC, CarolineF3 requested changes
Great job! :) It's a very ambitious and fun project. The code looks clean and nice, the naming is great as well.

2021-02-26 18:12 UTC, KarolCislowski requested changes
This is an awesome project! 🌈  However, I need to ask you for 2 changes:

1. change your concatenations to the template literals;
2. you were instructed to round your temperatures to the 1 decimal number, and you have 2.

2021-02-26 18:12 UTC, KarolCislowski commented on code/weather.js
> +  const API_urlCurrent = "https://api.openweathermap.org/data/2.5/weather?q=" + city + "&units=metric&lang=se&APPID=" + API_KEY;
We do not use string concatenation. You need to change it to template literals https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals 🤓

2021-03-04 06:17 UTC, KarolCislowski approved these changes
Great Job 🌈

2021-09-07 08:25 UTC, closed without merging