Project weather app - Felicia Liabäck Löwstett, Anna Lindgren
Technigo/project-weather-app pull request #173
Opened 2021-02-21 12:36 UTC by liaback-lowstett

Link to my deployed project: https://zealous-nightingale-04ef8c.netlify.app/

2021-02-24 11:14 UTC, Frivridna approved these changes
Reviewed by: Malin Göthe and Caroline Byström.

First of all we want to give you applause, the site looks great 👏! The result is very close to the Design-2 folder and looks very good in both mobile, tablet and desktop view. 

You did a detective work with the assets you used for different weather conditions, and reused that else if statement both for the mainDailyWeather and the weekForecast. In general the code is very clean, which makes it easy to read and follow along. That made our job a pleasure!  

A side note: We really appreciate that you added one of the weather icons for the Title in the index.html 😊
And the comments are useful to anyone who is reading your code, they are clear descriptions of the code to come below. 

We have also seen that the color changes for the background have changed, great job! 🙂

2021-02-24 11:14 UTC, Frivridna commented on code/script.js
> +               if (fetchDailyWeather === "Drizzle") {
Could there be an easier way to write all the if else? For example a switch statement. But we would have written it the same as you do today since we also don't feel comfy using switch yet. :)

2021-02-24 11:14 UTC, Frivridna commented on code/script.js
> +                    </div>`
Maybe check your indentation for the lines 35-83? :) It seems like it has been indented 2 tabs.

2021-02-24 12:55 UTC, Frivridna approved these changes

2021-02-24 12:55 UTC, Frivridna commented on code/script.js
> +        const sunriseHour = new Date((data.sys.sunrise)*1000).toLocaleTimeString('se-SE', {hour:'numeric', minute: 'numeric'})
It is written 'sv-SE' to format the time into a swedish time-format and not 'se-SE'. Since your entire app is in english maybe you ment to have 'en-US' or similar? :) It does not show in the browser since you get the default english here when 'se-SE' is incorrect.

2021-02-26 18:52 UTC, KarolCislowski requested changes
This is a very nice and clean project 🌈 

I need to ask you however for adding a decimal place to the temperature because it was one of the requirements to pass and to add the `catch()` to the second `fetch()`.

2021-02-26 18:52 UTC, KarolCislowski commented on code/script.js
> +        const roundedTemp = temp.toFixed() // no decimal
The instruction said it needs to be 1 decimal. Please change it 😸

2021-02-26 18:52 UTC, KarolCislowski commented on code/script.js
> +        console.log(fetchDailyWeather)
Please remember to always remove all logs and other elements that are helpful during coding but are not welcome in a finished project. 🗑️

2021-02-26 18:52 UTC, KarolCislowski commented on code/script.js
> +    .finally(() => console.log('Request finished'))
Yes, it is good to know it, but it is not a good practice to console.log something to your user.

2021-02-26 18:52 UTC, KarolCislowski commented on code/script.js
> +
Yes, you always should handle your errors with `.catch()`

2021-04-23 15:47 UTC, KarolCislowski approved these changes
Great project :)

2021-09-07 08:25 UTC, closed without merging