project-weather-app - Maria, Emma & Martin (Team Zebras)
Technigo/project-weather-app pull request #176
Opened 2021-02-21 20:06 UTC by MariaPogosjan

Link to my deployed project:

[https://weatheroracle.netlify.app/] 

My reflections on how this week's project turned out:
It went great, we had a really good team work and learned a lot from each other. Also I love love json. 

Things I'd like to have clarified or explained in more detail:
One thing we had problem with is that we get undefined on days in the forecast for day in mobile version. 
Don't know why and couldn't solve it.

2021-02-24 09:15 UTC, ettem approved these changes
We think this project can be approved and think that you did a really great job! Keep up the good work writing clean code that's easy to read!
/Mette & Maidelin

2021-02-24 09:15 UTC, ettem commented on code/script.js
> +    })
Good job catching API errors :)

2021-02-24 09:15 UTC, ettem commented on code/script.js
> +        document.querySelector('html').style.height = '1500px'
We wonder about the necessity of this height, in mobile version there is a huge area under the footer.

2021-02-24 09:15 UTC, ettem commented on code/script.js
> +}
Awesome job with this implementation!

2021-02-24 09:15 UTC, ettem commented on code/script.js
> +    console.log(selectedCity)
You could perhaps delete this console.log

2021-02-24 09:15 UTC, ettem commented on code/style.css
> +}
Good idea using this :root!

2021-02-26 19:19 UTC, KarolCislowski requested changes
It is an awesome project! 🌈  Please fix the decimal place issue I pointed in my comment ad it will be a small masterpiece 🦄

2021-02-26 19:19 UTC, KarolCislowski commented on code/script.js
> +      typeAndTemperature.innerHTML = `${weather.weather[0].main} | ${weather.main.temp.toFixed(0)}&#176C`
The instruction said that you need to present 1 decimal place 🤓

2021-02-28 20:50 UTC, MariaPogosjan commented on code/script.js
> +      typeAndTemperature.innerHTML = `${weather.weather[0].main} | ${weather.main.temp.toFixed(0)}&#176C`
Hi Karol! 

Thank you for your feedback. We have now added one decimal place as you requested. If you have any answer about why mobile version gives undefined on days, we would be grateful 🤓

2021-03-01 04:12 UTC, KarolCislowski approved these changes
Great job! 

What browser do you use on your mobile? Remember that Safari is a new IE... On my note20 with chrome browser, I can see all days normally. 🤓

2021-03-03 09:18 UTC, MariaPogosjan commented
Aah okey cool! I see 🙂 Thank you for your help!

*Allt gott, *
*Maria *

----------

Maria Pogosjan
Phone

|   +46 (0)73 69 14 411  <http://sdf/>




Den mån 1 mars 2021 kl 05:12 skrev Karol Cislowski <notifications@github.com
>:

> *@KarolCislowski* approved this pull request.
>
> Great job!
>
> What browser do you use on your mobile? Remember that Safari is a new
> IE... On my note20 with chrome browser, I can see all days normally. 🤓
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-weather-app/pull/176#pullrequestreview-600377896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKEYP2DMGFUWT5I5YPZQMTTBMH2DANCNFSM4X7KDNJA>
> .
>

2021-09-07 08:25 UTC, closed without merging