Weather app by Therese and Daniela
Technigo/project-weather-app pull request #177
Opened 2021-02-21 21:58 UTC by dannuzak

Link to my deployed project:

https://weather-app-therese-daniela.netlify.app

My reflections on how this week's project turned out:
At the beginning of this week, we had a pair programming session where we decided on what approach to use and how we would work. We checked the brief and the requirements and started step by step in order to first reach the blue level, and then also the red. We started with the fetch to display the current weather and then made another fetch for the forecast, where we filtered in order to get the relevant details, and made a loop for the five days. We also decided to fetch the weather icons directly from the API instead of using icons locally saved. After completing the basic requirements we started working on the red level, where we started with changing the color based on weather. We inserted the parts through JS but made the styling in CSS. We also added a fetch for other cities. In order to achieve this we used HTML, CSS and Javascript. We also worked with API and used json files in order to find the correct data to use. We also used media queries in order to make it responsive, and added a footer which is only visible on desktop.

Things I'd like to have clarified or explained in more detail:
How to work with fetched images a bit more in detail.

2021-02-24 11:16 UTC, esteficodes requested changes
Good job with this Weather app! It's great that you figured out the way to place the sunset and sunrise times locally, which represented a challenge, given the city you have chosen. Kudos! 💪🏻 //👱🏻‍♀️👩🏻

2021-02-24 11:16 UTC, esteficodes commented on code/style.css
> +}
Remember to always keep the same pattern (either use the one you used for: body. clear or the one you used for: body.sunny structure. 👩🏻‍💻

2021-02-24 11:16 UTC, esteficodes commented on code/script.js
> +    `;
Maybe a little bit coach assistance here, but we think it would be a good idea to put this three elements in different tags to have it easier to make them more responsive?

2021-02-26 19:25 UTC, KarolCislowski commented on code/script.js
> +  sunset.innerHTML += `${new Date((data.sys.sunset + data.timezone) * 1000).toLocaleTimeString('en-US',{hour: '2-digit', minute:'2-digit', hour12:false,})}`
inside the ${} you can divide your code as you want. The best way is to every part of a chained instructions starts in a new line. 
```
sunrise.innerHTML +=`
  ${new Date((data.sys.sunrise + data.timezone) * 1000)
    .toLocaleTimeString('en-US', {
      hour: '2-digit', 
      minute: '2-digit', 
      hour12:false,
    })}
`
```

2021-02-26 19:30 UTC, KarolCislowski approved these changes
This is a very nice project! 🌈  
I like the styling. Is nice and clean!
Estefania left you many nice tips and you should go through them and make your code clean like never 😸 

Great job!!

2021-03-05 08:17 UTC, dannuzak commented on code/style.css
> +}
Here for some reason the Prettier plug in was changing the format automatichally and against my will. 😖

2021-09-07 08:25 UTC, closed without merging