Project Weather App, Marielle Ohlsson & Katharina Liebig
Technigo/project-weather-app pull request #178
Opened 2021-02-23 16:08 UTC by katliebig

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-02-24 20:57 UTC, AsaHildebrand approved these changes
- Very nice explaining comments throughout the whole code, so it is easy to understand what you have done ! 
- Maybe check out the responsiveness, there shouldn't be any horisontal scrolling which seems to happen sometimes when we look at the dev tools, but we are not sure why. :)
- Very god job with this project, the weather app is looking really good!!
Regards //Erika, Johan and Åsa

2021-02-24 20:57 UTC, AsaHildebrand commented on code/script.js
> +    })
Nice solution here to get the different cities from line 12 and 47.

2021-02-24 20:57 UTC, AsaHildebrand commented on code/script.js
> +        `
These should probably move in a couple of steps :)

2021-02-24 20:57 UTC, AsaHildebrand commented on code/script.js
> +            }
Nice with this effect depending on time of day!

2021-02-24 20:57 UTC, AsaHildebrand commented on code/style.css
> +
Nice styling in CSS! :)

2021-02-26 19:35 UTC, KarolCislowski requested changes
This is a very nice and clean code🌈

Please fix the decimal place issue and it will be a great project!!

2021-02-26 19:35 UTC, KarolCislowski commented on code/script.js
> +            <h1>${Math.round(data.main.temp)}<span>°C</span></h1>
The instruction said that you need to round it to 1 decimal place. 🤓

2021-03-03 09:44 UTC, katliebig commented on code/script.js
> +            <h1>${Math.round(data.main.temp)}<span>°C</span></h1>
Thanks for the feedback! The issue is fixed now. :)

2021-03-04 06:15 UTC, KarolCislowski approved these changes
Great Job 🦄

2021-09-07 08:25 UTC, closed without merging