Sofias Weather App, Week 4 Web Dev Bootcamp spring 2024
Technigo/project-weather-app pull request #366
Opened 2024-03-01 16:30 UTC by sofia32057

## Netlify link
[https://sofias-weather-app.netlify.app/](https://sofias-weather-app.netlify.app/)

## Collaborators

2024-03-04 11:20 UTC, HIPPIEKICK requested changes
Beautifully executed Sofia! You've accomplished a lot this week; you followed the design closely and implemented extra feature's that still fits in well - like animations, the hamburger, the search bar etc.

One thing I would like you to fix is the responsiveness, as your content doesn't fit on a 320px screen:
- Make your app responsive (it should look good on devices from 320px width up to 1600px)

![Skärmavbild 2024-03-04 kl  12 20 16](https://github.com/Technigo/project-weather-app/assets/51529201/428fdb8b-f0c3-4b1b-b90e-cd7f10fe77ba)

2024-03-04 11:20 UTC, HIPPIEKICK commented on index.html
> +    <link
Nice!

2024-03-04 11:20 UTC, HIPPIEKICK commented on script.js
> +};
Nice solution!

2024-03-04 11:20 UTC, HIPPIEKICK commented on script.js
> +        <i class="weather-icon"><img src="https://openweathermap.org/img/wn/${obj.weather[0].icon}.png"/></i>
Seems to be working with the day/night icons 👍

2024-03-04 11:20 UTC, HIPPIEKICK commented on script.js
> +};
Beautiful!

2024-03-05 20:59 UTC, Citronskal reviewed
Hi Sofia, I am extremely impressed at your work! Your app is high-fidelity and user-friendly. Your codes are clean and easy to read. I learned so much for reviewing your codes. Keep up the amazing work!

2024-03-05 20:59 UTC, Citronskal commented on script.js
> +// Construct minutes and hours with two digits UTC
Impressive that you remember to convert the time to 2 digits! Took me a while to realize

2024-03-05 20:59 UTC, Citronskal commented on script.js
> +};
Second to this, it's very thoughtful and user-friendly to build this function. it shows that you treated it like a real application not just thinking about copying the design (which i did !)

2024-03-05 20:59 UTC, Citronskal commented on style.css
> +}
I am very impressed you defined CSS custom properties first to make the code clean.

2024-03-05 20:59 UTC, Citronskal commented on script.js
> +});
I loveee your animation, perhaps make the whole screen scrolls down as the forecast unfold will be nice?

scrollArrow.addEventListener("click", () => {
  toggleFullscreen(body);
  toggleHide(weatherForecast);
  window.scrollTo({
    top: window.innerHeight, 
    behavior: 'smooth' 
  });
});

2024-03-06 19:05 UTC, sofia32057 commented on script.js
> +// Construct minutes and hours with two digits UTC
Me too!

2024-03-06 19:06 UTC, sofia32057 commented on style.css
> +}
I love it, makes it so much easier!

2024-03-06 19:06 UTC, sofia32057 commented on script.js
> +});
YES! Great idea!

2024-03-12 13:36 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging