project-weather-app Viktoria O.
Technigo/project-weather-app pull request #367
Opened 2024-03-01 16:32 UTC by viktoria-olo

## Netlify link
https://marvelous-empanada-370879.netlify.app/

## Collaborators
Individual project

2024-03-04 14:55 UTC, jyy009 commented on index.html
> +        <table class="weather-today">
Cool that you used tables to structure it as I wouldn't have thought to do that!

2024-03-04 15:03 UTC, jyy009 commented on script.js
> +      if (weekday !== currentDay) {
Great that you figured how to compare the indexes to match the day with the temp!

2024-03-04 15:06 UTC, jyy009 reviewed
This looks awesome! It's super well organized, structured and was really easy to follow along. Also your variable names were informative which helped the follow along process. And I liked how your image is big on the right side when on desktop view.

2024-03-06 13:28 UTC, HIPPIEKICK requested changes
Interesting approach you've taken! It's working, so I won't ask you to change it - but I want to address that you're making multiple API calls to fetch the weather, city name, temperature, and sunrise/sunset data. It's repetitive (and we should try to follow the DRY principle). Next time, consider fetching all required data in a single API call and storing it in variables (or state in React which we will start talking about next week) for reuse.

What I _do_ want to ask you to change though is the layout on mobile. On 320px device width we get a tiny side scroll caused by the first cell in the table being a bit too wide. From requirements:
- Make your app responsive (it should look good on devices from 320px width up to 1600px)

Apart from that - it looks good and you're code is structured ⭐

2024-03-06 13:28 UTC, HIPPIEKICK commented on script.js
> +let forecastURL = `${BASE_URL}${forecastData}?q=${locale}&units=${units}&APPID=${API_KEY}`;
These could be constants I think?

2024-03-06 13:28 UTC, HIPPIEKICK commented on script.js
> +};
Could these be one function but with if/else statements instead base on a param? 👀 e.g.
```
const updateDesign = weather => {
  if (weather === "Rain") {
    //Logic
  }
}
```

2024-03-06 13:28 UTC, HIPPIEKICK commented on script.js
> +};
Nice with a switch! Another option is to make use of the indexes

2024-03-06 13:28 UTC, HIPPIEKICK commented on script.js
> +      if (weekday !== currentDay) {
Plus one on that 👍

2024-03-06 13:28 UTC, HIPPIEKICK commented on index.html
> +        <table class="weather-today">
Same ☝️

2024-03-12 13:37 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging