linda-f-project-weather-app
Technigo/project-weather-app pull request #369
Opened 2024-03-02 07:37 UTC by linda-f

## Netlify link
[https://linda-f-project-weather-app.netlify.app/]

## Collaborators
[linda-f]

2024-03-06 14:00 UTC, HIPPIEKICK requested changes
Good job with your weather app Linda! Just make sure it looks good on all devices (see how it looks in 320px width) to follow this requirement:
- Make your app responsive (it should look good on devices from 320px width up to 1600px)

2024-03-07 09:41 UTC, linda-f commented on code/style.css
> +  width: 375px;
I made it now responsive to 320px. I wasn't sure if we are allowed to do that since we needed to follow the design and there the container was 375px wide. ;)

2024-03-11 08:43 UTC, Izzibizz reviewed
Your app looks perfect! You did a great job styling and I really like that you added the background that made it your own. You've managed the code really well, and I only had a comment on the amount of styling js, just as Matilda. Otherwise your code is short, clear and easy to understand. Good job 💯 😃

2024-03-12 13:38 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging