Eliane Weather App | Week 4
Technigo/project-weather-app pull request #378
Opened 2024-03-02 16:32 UTC by El1an3

## Netlify link
https://elianes-weather-app.netlify.app/

## Collaborators
none, solo project

2024-03-05 17:25 UTC, sofia32057 reviewed
Awesome Eliane! Your app looks and works GREAT. 

For next project, I would suggest trying to divide the logic into smaller functions, to be a little more flexible. But whatever works 🔥

2024-03-05 17:25 UTC, sofia32057 commented on code/index.html
> +        />
Hey! Don't forget to remove commented out parts :)

2024-03-05 17:25 UTC, sofia32057 commented on code/index.html
> +    <header>by Eliane for Technigo Bootcamp</header>
This should probably be at <footer>?

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +      weatherToday.innerHTML = `<p>${
Could this function be broken up into smaller parts?

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +        throw new Error("Network is not responding");
Nicely done with error handling! 💪

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +          //If the day name doesn't already exist in the dailyForecasts object and the number of keys (representing the number of days) is less than 4, it stores the temperature for that day in the d
Clever! And really good comment, thanks!

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +        ].temp.toFixed(1)}°C</p></div>`;
Didn't know about the .toFixed method. Very handy. Thank you!

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +    });
Awesome! 🥳🙌

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +  const date = new Date((time + timezone) * 1000);
🤩

2024-03-05 17:25 UTC, sofia32057 commented on code/script.js
> +  const minutes = date.getUTCMinutes().toString().padStart(2, "0");
Clean!

2024-03-05 17:25 UTC, sofia32057 commented on code/style.css
> +body.warm .app-container {
Clever with warm and cold classes!

2024-03-07 09:32 UTC, HIPPIEKICK requested changes
Good job with the weather app Eliane! You followed most of the design and your code is quite structured too, I made some small comments of improvements.

One thing I need you to fix is the forecast, so that it displays the following four days (now it's displaying today + three days in the forecast) as per these requirements:
- The app should have: city name, current temperature, weather description, sunrise/sunset time, 4-day forecast
- The presentation of the data should be in the specified format

Feel free to reach out on SO if you need assistance.

2024-03-07 09:32 UTC, HIPPIEKICK commented on code/script.js
> +        document.getElementsByTagName("body")[0].classList = ["warm"];
You can always reach the body by writing `document.body`

2024-03-07 09:32 UTC, HIPPIEKICK commented on code/script.js
> +          //If the day name doesn't already exist in the dailyForecasts object and the number of keys (representing the number of days) is less than 4, it stores the temperature for that day in the d
Hmm, I don't think it's working as intended - it shows thu-sun but it should show fri-mon ⚠️

2024-03-07 09:32 UTC, HIPPIEKICK commented on code/script.js
> +    });
Agree, good error handling 👍

2024-03-07 09:32 UTC, HIPPIEKICK commented on code/script.js
> +};
⭐

2024-03-07 12:49 UTC, El1an3 commented on code/index.html
> +    <header>by Eliane for Technigo Bootcamp</header>
It was a footer and then I was lazy and reused the header-styling ;-)

2024-03-08 07:43 UTC, El1an3 commented on code/script.js
> +          //If the day name doesn't already exist in the dailyForecasts object and the number of keys (representing the number of days) is less than 4, it stores the temperature for that day in the d
fixed

2024-03-12 13:40 UTC, HIPPIEKICK commented
Now the forecast starts on Thursday instead of the coming day 👀

2024-06-13 09:23 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging