Week 4 - Weather App
Technigo/project-weather-app pull request #380
Opened 2024-03-02 22:01 UTC by ohitsnathalie

## Netlify link
https://nathalie-weather-app.netlify.app/

## Collaborators

2024-03-05 15:58 UTC, jingh999 reviewed
Very clean and smart writing! It is very inspiring. I like the way how you fetch the data and print the weather details. All works well except from the sunrise/sunset time. I also had too tight time to finish the stretch goals. Maybe it can be next step. But the city-function works well. Overall, great work!!

2024-03-05 15:58 UTC, jingh999 commented on script.js
> +  const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
I got the comments from my code review that this function can print the short name directly. It is good to know. data.toLocaleDateString('en-US', {weekday:'short'})

2024-03-05 15:58 UTC, jingh999 commented on script.js
> +    if (hours >= 18 || hours < 6) {
It would be even better that the background becomes night mode after sunset time and the background turns day mode after the sunrise.

2024-03-05 15:58 UTC, jingh999 commented on script.js
> +  const newForecastURL = `${API_BASE_URL}/forecast?q=${newCity}&units=metric&appid=${API_KEY}`;
Nice! Clean and flexible way to fetch the data.

2024-03-05 15:58 UTC, jingh999 commented on script.js
> +      <img class="icon" src="https://openweathermap.org/img/wn/${icon}@2x.png">
Very nice and easy way to show the icon of weather description!

2024-03-05 15:58 UTC, jingh999 commented on script.js
> +    const currentTimezoneOffset = data.timezone;
On the webpage,  the sunrise time and sunset time in all cities are one hour later than the real sunrise /sunset time.

2024-03-05 15:58 UTC, jingh999 commented on style.css
Looks nice! It could look even better on mobile devices.

2024-03-07 09:46 UTC, HIPPIEKICK requested changes
Well done implementing the design of the weather app. Your code looks structured as well, the only thing I would like you to fix is the forecast to show the correct dates - according to these requirements:

- The app should have: city name, current temperature, weather description, sunrise/sunset time, 4-day forecast
- The presentation of the data should be in the specified format

2024-03-07 09:46 UTC, HIPPIEKICK commented on index.html
> +      </select>
Nice!

2024-03-07 09:46 UTC, HIPPIEKICK commented on index.html
> +  <footer></footer>
Why an empty footer? 👀

2024-03-07 09:46 UTC, HIPPIEKICK commented on script.js
> +const printWeather = async weatherURL => {
Well named function!

2024-03-07 09:46 UTC, HIPPIEKICK commented on script.js
> +    if (hours >= 18 || hours < 6) {
Very good idea!

2024-03-07 09:46 UTC, HIPPIEKICK commented on script.js
> +      const highestTemp = Math.max(...temperatures).toFixed(0);
Neat!

2024-03-07 09:46 UTC, HIPPIEKICK commented on script.js
> +        .map(item => item.main.temp);
This forecast is showing Thu-Sun but it should be showing Fri-Mon, no?

2024-03-10 12:12 UTC, ohitsnathalie commented
@HIPPIEKICK the weekdays should be correct now and only showing from tomorrow onwards. I also deleted the empty footer. Initially, I had something there but decided not to put it.

2024-03-12 13:41 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging