Week 4- Weather app Etna
Technigo/project-weather-app pull request #383
Opened 2024-03-03 15:02 UTC by Caracal23

## Netlify link
[Netlify](https://earnest-gingersnap-d88be8.netlify.app/)

2024-03-04 17:35 UTC, Martin-Joensson reviewed
Great work Etna! I think you chose the design bravely and executed it very well! 

I can see a features-branch, did you do all your features in one branch or did you split them up and than deleted them? 

Your site functions well regardless of screen size, I think your might be able to tweak it for bigger screen. Right now there are very much white-space in the forecast for example. Making it harder to track the line you are on.

In terms of design I think the tweaks you did to accomidate the searchbar for example was really well done. It does not feel out of place. I also like that you used openWeathers Icons since the ones provided were a bit to few.

I'm super impressed and I just have to say: Great job once again and Go team Moon! =)

2024-03-07 14:58 UTC, AntonellaMorittu approved these changes
Hi Etna, very good job this week! Your code is well structured, the app is working well, you completed the basic requirements and added a search functionality, cool! One comment is about the forecast:

- The app should have: 4-day forecast

You are displaying all 5 days when we requested 4, not a big deal. Fix this and you're good to go:) Be careful when in mobile mode the button icon is squeezed and warped.  

Keep up the great work 🌞

2024-03-07 14:58 UTC, AntonellaMorittu commented on assets/.DS_Store
please delete and add to .gitignore 👍

2024-03-07 14:58 UTC, AntonellaMorittu commented on .DS_Store
🧹 🧹 🧹

2024-03-07 14:58 UTC, HIPPIEKICK requested changes
Good job this week Etna! Please have a look at how your app looks in 1600px width as per this requirement:
- Make your app responsive (it should look good on devices from 320px width up to 1600px)

I suggest you to put a max-width or in some other way add some padding to make it less stretched out:
<img width="1089" alt="Skärmavbild 2024-03-07 kl  15 58 43" src="https://github.com/Technigo/project-weather-app/assets/51529201/213e22b5-79ab-47a8-addf-1e25b175180e">

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +const currentWeather = (city) => {
Remember to name functions after what they do, e.g. fetchCurrentWeather

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +};
Agree!

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +const showForecast = (city) => {
Great name!

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +};
Nice! Have a look at how the button gets squeezed in one of the modes though

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +    });
Some kind of error handling would be good if the user searches for a city that doesn't exist

2024-03-07 14:58 UTC, HIPPIEKICK commented on script.js
> +const getWeekDay = (unixtime) => {
Could also be dealt with using indexes

2024-06-13 09:24 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging