Weather App Stockholm
Technigo/project-weather-app pull request #385
Opened 2024-03-03 16:19 UTC by lunek1

## Netlify link
https://65e4a10bb5d5f1a6a7b807cb--fantastic-piroshki-f776a2.netlify.app/

## Collaborators
Solo project, no collaborators.

2024-03-05 13:13 UTC, vittoriamatteoli commented on index.html
> +        <p>sunset <span id="sunset-time"></span></p>
to try a different approach, this could be implemented in the JS file.

2024-03-05 13:18 UTC, vittoriamatteoli commented on script.js
> +        };
nice! :)

2024-03-05 13:21 UTC, vittoriamatteoli reviewed
Nice job! The project fulfils the requirement and looks great, you reproduce the style perfectly! I would just delete all folders and files that you don't need.

2024-03-07 15:03 UTC, AntonellaMorittu requested changes
Hi Cornelia, very good job this week! Your code is well structured abnd formatted. The app is working as it should, you completed the basic requirements to pass this assignment. You can delete the design files to clean up the project? One comment is about the forecast: 

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4
- the temperature should be rounded to 1 decimal

Not a big deal. Fix these things and you're good to go:) 
Keep up the awesome work! 🌷

2024-03-12 13:42 UTC, HIPPIEKICK commented
Can you provide a working Netlify link please 😊

2024-03-12 13:52 UTC, lunek1 commented
Hi!
This is the link I updated on my github:
https://fanciful-melomakarona-4e6d38.netlify.app/

Sent with [Proton Mail](https://proton.me/) secure email.

On Tuesday, March 12th, 2024 at 14:42, Matilda Brunemalm ***@***.***> wrote:

> Can you provide a working Netlify link please 😊
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/Technigo/project-weather-app/pull/385#issuecomment-1991683182), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BEZQBFC72NNZ5W27S3IWW4TYX4A5BAVCNFSM6AAAAABEECLA52VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJRGY4DGMJYGI).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-08 14:08 UTC, lunek1 commented
> Hi Cornelia, very good job this week! Your code is well structured abnd formatted. The app is working as it should, you completed the basic requirements to pass this assignment. You can delete the design files to clean up the project? One comment is about the forecast:
> 
> * The app should have: 4-day forecast You are displaying all 5 days when we requested 4
> * the temperature should be rounded to 1 decimal
> 
> Not a big deal. Fix these things and you're good to go:) Keep up the awesome work! 🌷

2024-05-08 14:10 UTC, lunek1 commented
> Hi Cornelia, very good job this week! Your code is well structured abnd formatted. The app is working as it should, you completed the basic requirements to pass this assignment. You can delete the design files to clean up the project? One comment is about the forecast:
> 
> * The app should have: 4-day forecast You are displaying all 5 days when we requested 4
> * the temperature should be rounded to 1 decimal
> 
> Not a big deal. Fix these things and you're good to go:) Keep up the awesome work! 🌷

Hi! Can you please check the changes I made and see if I met the requirements now. Also let me know if my netlify link is working for you. ✨

2024-06-07 08:54 UTC, AntonellaMorittu commented
Hi Cornelia, the PR is closed and I cannot approve it, please open it again 👍

2024-06-10 11:56 UTC, lunek1 commented
> Hi Cornelia, the PR is closed and I cannot approve it, please open it again 👍

I didn't even know I had closed. It's open now 😅

2024-06-13 09:24 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging