Yia - weather app - design 2
Technigo/project-weather-app pull request #386
Opened 2024-03-03 16:43 UTC by Citronskal

## Netlify link
[https://yias-weather-app.netlify.app)https://yias-weather-app.netlify.app/]

## Collaborators
Add your collaborators here. Write their GitHub usernames in square brackets. If there's more than one, separate them with a comma, like this:
[none]

2024-03-05 20:41 UTC, Yifan-858 commented
Hey Yia, great work! Your code has a well-organized structure. That makes it very easy to follow along! The app loads quickly and the weather data is retrieved efficiently. Overall, your project meets the requirements. Keep going!

2024-03-05 20:45 UTC, Yifan-858 commented on code/Design 2/index.js
> +      const { currentWeather, forecast } = await getWeather(city);
Super efficient to use async/await to avoid callback hell!

2024-03-05 20:52 UTC, Yifan-858 commented on code/Design 2/index.js
> +  const forecastUrl = `https://api.openweathermap.org/data/2.5/forecast?q=${city}&appid=${apiKey}`;
"&units=metric" can be added to the URL("api.openweathermap.org/data/2.5/weather?q=${city}**_&units=metric_**&appid=${apiKey}") to get Celsius temperature data as mentioned in Open weather API doc. That will save you some lines for converting the units of the temp :)

2024-03-05 20:58 UTC, Yifan-858 commented on code/Design 2/index.js
> +  }
Being a bit nitpicky here, I will keep the styling parts in the CSS file to make the codes easier to maintain and read for the other developers in the future. :)

2024-03-05 21:07 UTC, Yifan-858 commented on code/Design 2/index.js
> +  weatherBackground.appendChild(errorDisplay);
Good idea to add an error message!

2024-03-05 21:09 UTC, Yifan-858 commented on code/Design 2/style.css
> +  margin-bottom: 20px; /* Add bottom margin */
margin can be combined like this: 
`margin: 20px auto;`

2024-03-07 15:09 UTC, AntonellaMorittu requested changes
Hi Yia, very good job this week! Your code is well structured and formatted and the app is working well, you completed the basic requirements + search bar⭐ 
There are a couple of things to fix to meet the requirements:

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal
- the UI needs to follow the design as close as possible

Not a big deal. Fix this and you're good to go:) Keep up the awesome work 🚀

2024-03-08 12:31 UTC, AntonellaMorittu requested changes
Nice fixing the decimals, now last thing to fix is the layout for mobile, it's offset (see screenshot) please fix this, almost there 💪 
<img width="372" alt="Screenshot 2024-03-08 at 13 30 22" src="https://github.com/Technigo/project-weather-app/assets/33493978/a18adf76-c1cc-4930-942d-1227699f6ea0">

2024-03-12 13:43 UTC, HIPPIEKICK commented
Still the same. Feel free to reach out on SO if you need help/inspiration 😊 

<img width="698" alt="Skärmavbild 2024-03-12 kl  14 43 09" src="https://github.com/Technigo/project-weather-app/assets/51529201/a5ccd5f3-04d5-4be6-99b1-8493ac883ad9">

2024-03-12 17:23 UTC, Citronskal commented
@HIPPIEKICK I fixed the issue I think, can you take a look for me? Thank you!

2024-03-13 16:19 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging