Alex's weather app (required functions are there, but not finished with CSS styling)
Technigo/project-weather-app pull request #388
Opened 2024-03-03 18:24 UTC by Xikitita

## Netlify link
https://idyllic-maamoul-97c14d.netlify.app/

2024-03-06 15:33 UTC, Tejpex reviewed
Great that the app is working and the code is clean!

Obviously the styling isn't finished, so I have disregarded that part.

2024-03-06 15:33 UTC, Tejpex commented on index.html
> +      <div class="typeofweather" id="typeOfWeather">Loading weather...</div>
Good with a default text!

2024-03-06 15:33 UTC, Tejpex commented on script.js
> +const BASE_URL = "https://api.openweathermap.org/data/2.5/weather?q=Stockholm,Sweden&units=metric&APPID=343b966846b558ccc45becaa3d348154"
Does the API-key need to be written twice, or could this be shorter?

2024-03-06 15:33 UTC, Tejpex commented on script.js
> +    const sunriseTime = (`${sunriseHour}:${sunriseMinutes}`)
With this code the time "18:05" is displayed as "18:5" which is somewhat confusing. I had to fix this in my own code using an if statement like this:

`if (sunriseMinute < 10) {
    sunriseMinuteAdjusted = `0${sunriseMinute}`
  } else {
    sunriseMinuteAdjusted = sunriseMinute
  }
const sunriseTime = `${sunriseHour}:${sunriseMinuteAdjusted}``

2024-03-06 15:33 UTC, Tejpex commented on script.js
> +    })
Good way to find only the forecasts from 12 o'clock!

2024-03-06 15:33 UTC, Tejpex commented on script.js
> +    const temperatureFiveDays = data.main.temp.toFixed(0)
Should it be no decimals in the forecast or should it be one decimal here as well?

2024-03-06 15:33 UTC, Tejpex commented on script.js
> +    const fiveDaysList = currentDate.toLocaleDateString('en-US', {weekday: 'short'})
Does this write the weekdays Mon, Tue, Wed etc?
If so, I learned something new :)

2024-03-07 06:51 UTC, Xikitita commented on script.js
> +const BASE_URL = "https://api.openweathermap.org/data/2.5/weather?q=Stockholm,Sweden&units=metric&APPID=343b966846b558ccc45becaa3d348154"
Very good input. Will look into that!

2024-03-07 15:18 UTC, AntonellaMorittu requested changes
Hi Alex, good job submitting your project! Have you tested the app before opening the PR? There is no icons displayed 😢 

Please consider these requirements:
- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal
- the app should follow as close as possible the chosen design

Take a look again at your code carefully and fix the issues pls, thank you ⭐

2024-09-17 12:46 UTC, closed without merging