Project-weather-app
Technigo/project-weather-app pull request #391
Opened 2024-03-03 20:23 UTC by Paulajungaker

## Netlify link
https://weatherforecastbypaula.netlify.app/

## Collaborators

2024-03-06 15:00 UTC, schouenkes commented on index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
Nice that you use this, I'll have that in mind for future projects.
```   <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

2024-03-06 15:15 UTC, schouenkes commented on script.js
> +    const degrees = Math.round(json.main.temp);
I see that you have rounded the temp to the nearest integer. To meet the requirements you need to show the temperature with one decimal at some place on the webpage. I used the method toFixed() to accomplish this task, hopefully it will work for you to.

2024-03-06 15:25 UTC, schouenkes commented on script.js
> +const sunny = () => {
Readable function which just handle the design and updating the html. Easy to understand and follow.

2024-03-06 15:33 UTC, schouenkes commented on script.js
> +   function convertTime(timestamp) {
I see that you have used the arrow function expression for your functions except for this function, for consistent it could be changed into the arrow function expression as well.

2024-03-06 15:57 UTC, schouenkes reviewed
For me it's readable code that doesn't repeat it self and you have named the function, classes and ids well.

To meet the requirement I just think you have to change one temperature to be shown with one decimal.

Even if you encountered some problems on the way, you solved them and have created a web page that follows the chosen design and work as intended, be proud! 💪🤩

2024-03-07 15:26 UTC, AntonellaMorittu requested changes
Hi Paula,very good job this week! Your code is well structured and the app is working as it should 👍 Some things need to be fixed to meet the basic requirements: 
- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal Not a big deal. 
- the forecast temperature should either be max/min or if you're displaying other ranges make sure it reflects to the UI in a clear and univocal way

Fix these things and you're good to go:) Keep up the awesome work 🚀

2024-03-07 15:26 UTC, AntonellaMorittu commented on script.js
please delete the console.log() when not needed and format the code 👍

2024-03-07 15:26 UTC, AntonellaMorittu commented on index.html
please format the code to have 2-tabs and reduce empty spaces 🧹

2024-03-07 15:26 UTC, AntonellaMorittu commented on script.js
> +
please remove the empty lines using a formatted (Prettier?) :)

2024-03-07 15:26 UTC, AntonellaMorittu commented on styles.css
please format the stylesheet too 🪄

2024-04-02 09:21 UTC, AntonellaMorittu requested changes
Hi Paula, great you fixed some issues! Don't forget the forecast need to display the next 4 days (so not the current day forecast). Still left to adjust the temperature ranges to be displayed in the forecast. Almost there :)

2024-04-05 08:03 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging