Weather app - Mai
Technigo/project-weather-app pull request #392
Opened 2024-03-03 21:17 UTC by maikanetaka

## Netlify link
https://maik-weather-app.netlify.app/

2024-03-06 09:53 UTC, Caracal23 approved these changes

2024-03-06 09:53 UTC, Caracal23 commented on script.js
> +function handleError(error) {
Good that you are logging the error.

2024-03-06 09:53 UTC, Caracal23 commented on script.js
> +    const days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
I like that you approach the days in an array ☺️

2024-03-06 09:53 UTC, Caracal23 commented on script.js
your code is well structured and clean, which makes it easy to read and understand-

2024-03-06 09:53 UTC, Caracal23 commented
Great work Mai!!

2024-03-07 15:29 UTC, AntonellaMorittu requested changes
Hi Mai, very good job this week! Your code is well structured and formatted. The app is working as it should, you completed the basic requirements to pass this assignment. Is the search bar not working? Then please delete if not fully functional 👍  One comment is about the basic requirements: 

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal 

Not a big deal, fix these things and you're good to go:) Keep up the awesome work 🎸

2024-03-07 15:29 UTC, AntonellaMorittu commented on .DS_Store
please delete all the .DS_Store files 🧹

2024-03-07 15:29 UTC, AntonellaMorittu commented on script.js
> +  )
please delete 🧹

2024-06-18 21:05 UTC, maikanetaka commented
Hello! @AntonellaMorittu, I have fixed to be 4 days forecast and 1 decimal. Please check!

2024-06-19 14:07 UTC, AntonellaMorittu commented
Hey Mai! Did you deploy using another link or is the one submitted valid? I can't see the changes, please double-check, thank you

2024-06-20 10:14 UTC, maikanetaka commented
Hi @AntonellaMorittu Sorry for that! I manually deployed and now it should work.  https://maik-weather-app.netlify.app/ please check!

2024-06-24 08:13 UTC, AntonellaMorittu requested changes
Hey Mai, great almost there, still missing:
- the temperature should be rounded to 1 decimal

2024-06-25 21:00 UTC, maikanetaka commented
Hi @AntonellaMorittu, I have changed to 1 decimal. Please check.

2024-06-26 07:55 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging