project weather app
Technigo/project-weather-app pull request #395
Opened 2024-03-03 22:07 UTC by kathinka

## Netlify link
 Netlify link [here](https://oslo-weather.netlify.app/).

2024-03-04 12:41 UTC, lunek1 reviewed
Hi Kathinka! Just looked at your weather app and code is working fine! As far as I can tell you've checked all the requirements and followed the guidelines. I liked that you added more data, forecast for coming days and what the temperature feels like. It give a really nice touch to the webpage!

Some comments:
- The temperature is rounding to whole numbers if I'm not mistaken. In that case for visual purposes it would be easier on the eyes if you had 0 decimal places.
- There are two small white boxes on each side of the weekdays which I'm guessing isn't suppose to be there. Might be something in CSS that is causing it. 
- Adding a few a comments to your code would help to make it easier to understand its logic and functions and kind of guide you through it upon reviewing it.

Good job on your project and thanks for letting me review it! 🌻

2024-03-04 16:14 UTC, kathinka commented
Hi Cornelia! Thanks for reviewing! the task for step two said to display "the temperature (rounded to 1 decimal place)" but I agree - it would look better with only one digit.
I'll look into adding some comments in my code as well. 
as for the styling bug I would like some more info (browser, os and device) as I cant reproduce it, but would like to fix it!

Thanks for all the comments :)

2024-03-08 08:44 UTC, lunek1 commented
Hi! Sorry for late respond!
 "the temperature (rounded to 1 decimal place)" - I apparently missed this step. It looks so messy (perfectionist here) but okey then you are all good! 🌻
 I also checked in on the css glitch or whatever it could be. I looked at your weather app again but on two other computers (mac and pc) and I couldn't see it. However I can still see it on my laptop. I can't figure out what is causing it so It's probably nothing. Don't worry about it. Good job again! 🙌✨

2024-03-08 10:10 UTC, AntonellaMorittu requested changes
Hello Kathinka, good job this week! The app is working as it should, you completed almost all the basic requirements to pass this assignment. Please consider this:

- the app should follow as close as possible the chosen design
[this](https://github.com/Technigo/project-weather-app/blob/master/design/design2/iPhone%20X-XS%20%E2%80%93%201.png) was the reference, on mobile your app should look exactly like this.

Please update the UI and you're good to go 🚀 Thank you ⭐

2024-03-08 10:10 UTC, AntonellaMorittu commented on design/.gitignore
.gitignore should live in the root folder, outside of any others. Please move it outside of the design folder 👍

2024-03-08 10:10 UTC, AntonellaMorittu commented on index.html
please format your code using 2tabs spacing 🪄

2024-03-08 10:10 UTC, AntonellaMorittu commented on script.js
same here, format the code using 2tabs spacing and improve readability 👍

2024-03-09 23:27 UTC, kathinka commented on design/.gitignore
woops, thank you for catching that

2024-03-09 23:34 UTC, kathinka commented on index.html
done

2024-03-09 23:34 UTC, kathinka commented on script.js
done

2024-03-09 23:35 UTC, kathinka commented
All changes have been implemented

2024-03-12 13:48 UTC, HIPPIEKICK commented
Consider removing some parts in the mobile view, because it doesn't fit right now:

<img width="436" alt="Skärmavbild 2024-03-12 kl  14 47 58" src="https://github.com/Technigo/project-weather-app/assets/51529201/efc27061-11f8-48d5-b256-ab130fa60e0e">

2024-03-12 17:56 UTC, kathinka commented
Aha - what device, os and browser is this? it did not have this issue when
I tested it earlier.  but ok, good suggestion.

tir. 12. mars 2024 kl. 14:49 skrev Matilda Brunemalm <
***@***.***>:

> Consider removing some parts in the mobile view, because it doesn't fit
> right now:
> Skarmavbild.2024-03-12.kl.14.47.58.png (view on web)
> <https://github.com/Technigo/project-weather-app/assets/51529201/efc27061-11f8-48d5-b256-ab130fa60e0e>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-weather-app/pull/395#issuecomment-1991696272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBHIX25XCIKEP2IWNI3ARLYX4BU7AVCNFSM6AAAAABEEJE6NCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJRGY4TMMRXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-12 18:29 UTC, kathinka commented
fixed it! (but would still like to know device, os and browser :) )

> Consider removing some parts in the mobile view, because it doesn't fit right now:
> 
> <img alt="Skärmavbild 2024-03-12 kl 14 47 58" width="436" src="https://private-user-images.githubusercontent.com/51529201/312100557-efc27061-11f8-48d5-b256-ab130fa60e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjgzNzMsIm5iZiI6MTcxMDI2ODA3MywicGF0aCI6Ii81MTUyOTIwMS8zMTIxMDA1NTctZWZjMjcwNjEtMTFmOC00OGQ1LWIyNTYtYWIxMzBmYTYwZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE4Mjc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTdjMjc1MTEzNTc1NTI3MjAwYmU3NGM2ODZlMWNjZmMzNDE1ZjU0NWM2Yzc1ZjU1ZGJhZjIwZmJkZjYzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1r-OWLksMF-sZAKbI30QqAp_ootXnSWJ3tV-mTc8wbM">

2024-03-13 15:59 UTC, HIPPIEKICK approved these changes
Good job implementing the changes ⭐
For transparency, I used iPhone 5/SE dimenstions in the Chrome inspector, but I have a similar narrow phone (Xperia).

2024-06-15 16:53 UTC, kathinka commented
@AntonellaMorittu & @HIPPIEKICK care to take a second look? :)

2024-09-17 12:46 UTC, closed without merging