W4-Project-Weather-App
Technigo/project-weather-app pull request #396
Opened 2024-03-03 22:25 UTC by jingh999

[jingh999]

2024-03-05 14:16 UTC, trista1987 reviewed
Very clean writing, it was easy to follow and understand. I like the way how did you write for the image, also leanred another way to write the time. Nice layout and reached the responsive design. Good job!

2024-03-05 14:16 UTC, trista1987 commented on script.js
> +                console.log(myHour)
Don't forget to delete console.log. (I got the same comment from my code)

2024-03-05 14:16 UTC, trista1987 commented on script.js
> +                        max_temp: maxTemp
It is nice to be reminded that we can make an object.

2024-03-05 14:16 UTC, trista1987 commented on script.js
> +                if (currentHour === myHour || currentHour === myHour + 1 || currentHour === myHour - 1) {
I just learned that you can also use `data.timezone()` for the local time.

2024-03-05 14:16 UTC, trista1987 commented on script.js
> +const dayNames=['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat']
I used `data.toLocaleDateString('en-US', {weekday:'short'})`, so the day will be printed short name directly, such as Mon, Tue. But then it will be a totally different way to write the code.

2024-03-08 10:22 UTC, AntonellaMorittu requested changes
Hello Jing, very good job this week! Your code is well structured and the app is working as it should. You can delete the design files to clean up the project? Is the search bar working? if not please remove it, only leave functioning elements in the UI.

Please pay attention to these basic requirements:

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal 

Fix these things and you're good to go:) Keep up the awesome work 🚀

2024-03-08 10:22 UTC, AntonellaMorittu commented on .DS_Store
please delete all the .DS_Store files and add it to .gitignore 👍

2024-03-08 10:22 UTC, AntonellaMorittu commented on index.html
please format to 2tabs spacing 🪄

2024-03-08 10:22 UTC, AntonellaMorittu commented on script.js
here too, please format to 2tabs spacing 🪄

2024-03-08 10:22 UTC, AntonellaMorittu commented on style.css
here too, please format to 2 tabs spacing 🪄

2024-03-12 13:50 UTC, HIPPIEKICK commented
Have another look at mobile view, make sure everything fits (not sure how it looked before):
<img width="629" alt="Skärmavbild 2024-03-12 kl  14 49 17" src="https://github.com/Technigo/project-weather-app/assets/51529201/f83df4e8-e6b6-4354-9423-82dfc6b6d431">

2024-05-04 09:02 UTC, jingh999 commented
> Have another look at mobile view, make sure everything fits (not sure how it looked before): <img alt="Skärmavbild 2024-03-12 kl 14 49 17" width="629" src="https://private-user-images.githubusercontent.com/51529201/312101047-f83df4e8-e6b6-4354-9423-82dfc6b6d431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzgzNTksIm5iZiI6MTcxNDczODA1OSwicGF0aCI6Ii81MTUyOTIwMS8zMTIxMDEwNDctZjgzZGY0ZTgtZTZiNi00MzU0LTk0MjMtODJkZmM2YjZkNDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEyMDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODY2MjNiNTA2OTJmZDBmODA3NWI4OWU2OWZmNGJjZTg4MWNhYWNjMGRkNDU5YjY2NTQzMzc5OTkxNDMyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nn2tBOcZ_QAzeGmvIiPnaSce_E1DvUQ6MLDvXHcg73E">

2024-05-04 09:04 UTC, jingh999 commented
> Have another look at mobile view, make sure everything fits (not sure how it looked before): <img alt="Skärmavbild 2024-03-12 kl 14 49 17" width="629" src="https://private-user-images.githubusercontent.com/51529201/312101047-f83df4e8-e6b6-4354-9423-82dfc6b6d431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTM3MzQsIm5iZiI6MTcxNDgxMzQzNCwicGF0aCI6Ii81MTUyOTIwMS8zMTIxMDEwNDctZjgzZGY0ZTgtZTZiNi00MzU0LTk0MjMtODJkZmM2YjZkNDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA5MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZjM1YTRhMWNiNDRkOTMzNWNiNmFmNzYwZmQyYmM4NmFhNjdjNmNhYzcyZmZjYzE3OTEwZDAwMWYyOWJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BuCIGjN-OZm0jTF8xbWfg25XqgyBu-KUS0PDg-oF6yA">

fixed

2024-05-17 09:27 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging