Weather app Sofie - not done.
Technigo/project-weather-app pull request #399
Opened 2024-03-04 07:19 UTC by SofieFerrari

## Netlify link
(https://deluxe-smakager-88132e.netlify.app/)

solo

2024-03-06 15:55 UTC, almaherris reviewed
Hej Sofie! I know this week was hard and that you've been sick, so really good job accomplishing this much! 

Looking at the requirements, it seems like you completed 
✅ fetch data from the API using `fetch()`
✅ present city name, temperature and type of weather (just remember to display temp with one decimal!)
✅ work in branches
✅ follow one of the designs
✅ sunrise and sunset data

To complete:
🌦 Weather forecast
🌦 finish styling
🌦 responsiveness

Sooo I think you've completed more than you think and once you have some time, you'll be able to do fix the remaining requirements 💪

2024-03-06 15:55 UTC, almaherris commented on code/index.html
> +			alt="umbrella"/>
I think it would be easier to only have the img-container here and then change the icon directly in JavaScript depending on the weather, then you only would have had to write the HTML code once :)

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +const errorDiv = document.getElementById('error')
Nice keeping all your DOM selectors on top, makes it easy to have an overview!

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +	)
You could also have stored the API adress separately above the function like Matilda showed in class (like this: const BASE_URL = "https://...." and then fetch(BASE_URL).. I don't know if it's better but I think it looks clean and it's probably good if you want to reuse the URL.

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +			console.log(data)
I know this code is work in progress but if you decide to finish later, remove console.logs :)

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +	const temp = Math.trunc(data.main.temp)
I didn't know about Math.trunc but I just read that it removes decimals. Part of the assignment was to add 1 decimal, I think it would be easiest to add that here when declaring the temp 😊 I used the method .toFixed(1) for this purpose - "1" means we want one decimal.

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +	})
This seems to be working well, nice 😎 How about naming these variables a bit more descriptive, like sunrise or sunriseTime? Especially the variable "set" made me confused for a second before I realized it's short for "sunset" 🌆

2024-03-06 15:55 UTC, almaherris commented on code/style.css
> +}
Smooth and easy way to keep track of all your colors, I like it!

2024-03-06 15:55 UTC, almaherris commented on code/script.js
> +	})
I think that, rather than hiding the images here, it would be easier to treat them in the same way as you did with the weather specific texts, meaning you don't have them in your HTML but only show them when you need them. So for example for the scenario (weather === 'Clear') you would write something like this:

cityContainer.innerHTML = `<h1>Get your sunnies on. Umeå is looking rather great today.</h1>`
icons.innerHTML = url("./images/sunglasses") <-- not exactly like this maybe but you get the idea?

Just an idea that would perhaps make it easier to follow and keep track of where you're changing your HTML 😌

2024-03-06 15:55 UTC, almaherris commented on code/style.css
> +/* Background color */
I like that you left comments so it's easy to follow which section you're styling 💃

2024-03-06 15:55 UTC, almaherris commented on code/style.css
> +	justify-content: flex-end;
This makes your text stick to the right side which looks a bit strange when you're on desktop. It looks fine on the phone but I think it would look better with "flex-start" or center 😇

2024-03-06 15:55 UTC, almaherris commented on code/style.css
> +}
Your app looks good on phone but not on desktop 🖥  Maybe it's easier to do mobile-first, I think that might be the easiest way to approach it since we were provided with the mobile design. And then just make it look ok on desktop too 🤩

2024-03-06 15:55 UTC, almaherris commented on README.md
> +It is far from done. Nothing is in place.
Just for the record, I saw this note and I reviewed it in it's current state, knowing it's not done yet 🌝

2024-03-08 10:35 UTC, AntonellaMorittu requested changes
Hello Sofie, good job implementing your weather app - even if not completed!
You can continue to work on that, and please keep in mind the basic requirements:

- The app should have: city name, current temperature, weather description, sunrise/sunset time
- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- The temperature should be rounded to 1 decimal 
- Make your app responsive (it should look good on devices from 320px width up to 1600px)
- Follow one of the designs as closely as you can
- Follow the guidelines on [how to write good code](https://www.notion.so/Guidelines-for-how-to-write-good-code-59abdd4307a24f5ca7914d566326f4df?pvs=4)

You can make it 🔥 if you need help reach out without hesitation, describing specifically the problem ⭐

2024-03-12 13:55 UTC, HIPPIEKICK commented
Keep up the good work Sofie! 🔥 Just a little bit left:

- <s>The app should have: city name, current temperature, weather description, sunrise/sunset time</s>
- <s>The app should have: 4-day forecast You are displaying all 5 days when we requested 4</s>
- <s>The temperature should be rounded to 1 decimal</s>
- Make your app responsive (it should look good on devices from 320px width up to 1600px)
  - Have a look at how your app looks in the extremes (320px and 1600px) and make sure it looks good
- Follow one of the designs as closely as you can
  - The icons seem to be broken?
- <s>Follow the guidelines on [how to write good code](https://www.notion.so/Guidelines-for-how-to-write-good-code-59abdd4307a24f5ca7914d566326f4df?pvs=4)</s>

2024-05-17 09:26 UTC, AntonellaMorittu approved these changes

2024-09-17 12:46 UTC, closed without merging