Funky Weather Forecast
Technigo/project-weather-app pull request #401
Opened 2024-03-04 10:33 UTC by Izzibizz

## Netlify link
Add your Netlify link here.
PS. Don't forget to add it in your readme as well.

## Collaborators
Add your collaborators here. Write their GitHub usernames in square brackets. If there's more than one, separate them with a comma, like this:
[github-username-1, github-username-2]

2024-03-05 18:56 UTC, wwenzz reviewed
Your design is amazing 🤩!!! I like how you style the background based on the weather and it looks very cool. Your code also looks neat and clean - love it! Just one small suggestion - I didn't see you round any numbers to 1 decimal place, maybe this is something you could look into and challenge yourself to find a solution?

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +  array.forEach((day) => {
I would use arr instead of array as that's probably a reserved word.

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +  const rise = new Date(data.city.sunrise * 1000).toLocaleTimeString([], {
Nice function choice!

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +    .catch((error) => console.log('error fetching data', error))
nice catch!

2024-03-05 18:56 UTC, wwenzz commented on style.css
> +::-ms-input-placeholder {
I like how you manage this selector to control the placeholder styling for IE browser.

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +  if (event.key == 'Enter') {
what if the user doesn't input anything? could this also be a condition checked by if else statement?

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +const styleAfterWeather = (weather, temp) => {
Great styling function!

2024-03-05 18:56 UTC, wwenzz commented on script.js
> +  console.log(fourDaysFilter)
would be better to remove those two console.log as these are mainly for development purposes.

2024-03-08 12:13 UTC, AntonellaMorittu requested changes
Hi Izabel, good job finishing your assignment! 

Please pay attention to these basic requirements:

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal 
- the app should follow as close as possible the chosen design

Fix these things and you're good to go:) Keep up the awesome work 🚀

2024-09-17 12:46 UTC, closed without merging