Weather app
Technigo/project-weather-app pull request #403
Opened 2024-03-04 19:17 UTC by Antontall

## Netlify link
https://teal-blancmange-25a098.netlify.app

## Collaborators
This was a solo project.

2024-03-07 19:48 UTC, JohannaBN reviewed
Nice app that looks really good and well structured code that is easy to follow!

2024-03-07 19:48 UTC, JohannaBN commented on fetch.js
> +const currentWeatherIcon = document.getElementById("weather-icon");
Nice structured with APIs and DOM Selectors on the top. Makes it very easy to read!

2024-03-07 19:48 UTC, JohannaBN commented on fetch.js
> +        // Convert sunrise and sunset data into Date obejcts
Really nice with all the comments!

2024-03-07 19:48 UTC, JohannaBN commented on index.html
> +            </div>
Could this have been done without having to repeat the code?

2024-03-07 19:48 UTC, JohannaBN commented on style.css
> +    background: linear-gradient(90deg, #8589FF 0%, #E8E9FF 100%);
Nice fading background!

2024-03-07 19:48 UTC, JohannaBN commented on style.css
> +    margin: 50px auto;
Is it this margin that makes the app have a white field all around? Maybe this one could be removed from the top on smaller screens to prevent scrolling?

2024-03-08 12:15 UTC, AntonellaMorittu requested changes
Hi Anton, good job finishing your assignment! Please pay attention to these basic requirements:

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the app should follow as close as possible the chosen design
- the code needs to follow the guidelines of writing good code (formatting is part of it, please format to two-space tab indentation 🪄 )

Fix these things and you're good to go:) Keep up the awesome work 🚀

2024-09-17 12:46 UTC, closed without merging