Project-weather-app
Technigo/project-weather-app pull request #407
Opened 2024-03-06 16:13 UTC by Looziolooz

## Netlify link
Add your Netlify link here.
PS. Don't forget to add it in your readme as well.
https://lorenzoweatherapp.netlify.app/

## Collaborators
Add your collaborators here. Write their GitHub usernames in square brackets. If there's more than one, separate them with a comma, like this:
[github-username-1, github-username-2]

2024-03-08 12:22 UTC, AntonellaMorittu requested changes
Ciao Lorenzo, very good job this week! Your code is well structured and the app is working as it should - almost. Have you tested the search functionality with different cities? Sunrise and sunset times need to be adjusted :) That was a stretch goal so you don't need to fix it to pass the assignemnt.

However, please pay attention to these basic requirements:

- The app should have: 4-day forecast You are displaying all 5 days when we requested 4 
- the temperature should be rounded to 1 decimal 
- the app should follow as close as possible the chosen design

Fix these things and you're good to go:) Keep up the awesome work 🚀

2024-03-08 12:22 UTC, AntonellaMorittu commented on fetch2.js
> +function fetchWeather(city) {
although this is correct, please note during the bootcamp we're using the Arrow Functions (const () => {}) approach to define functions 👍

2024-03-12 20:40 UTC, Maria-Manuela commented on script.js
> +      const sunsetTime = new Date(data.sys.sunset * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
Sunrise and sunset it is not displayed, check the element IDs  in the HTML if there are accessible to JS code

2024-03-12 20:45 UTC, Maria-Manuela commented on script.js
> +  if (event.key === 'Enter') {
the code snippet is well-written and serves its purpose effectively

2024-03-12 20:52 UTC, Maria-Manuela reviewed
Well done, Lorenzo! The code is well-written and functional. However, there are a few areas that need attention. Address the errors appearing in the console, fix the display of sunrise and sunset times, and ensure that you follow the project instructions.

2024-03-13 09:40 UTC, Looziolooz commented on fetch2.js
> +function fetchWeather(city) {
Hi Antonella, thank you for pointing that out. Updated✔️

2024-03-13 09:43 UTC, Looziolooz commented on script.js
> +      const sunsetTime = new Date(data.sys.sunset * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
Hi Maria, I had left them hidden so I could edit them later. They are now visible. Thank you!

2024-03-13 09:43 UTC, Looziolooz commented on script.js
> +  if (event.key === 'Enter') {
Thank you!!

2024-03-18 16:15 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging