Martin Weather App
Technigo/project-weather-app pull request #408
Opened 2024-03-07 09:37 UTC by Martin-Joensson

## Netlify link

https://weathersmeather.netlify.app/

## Collaborators
Add your collaborators here. Write their GitHub usernames in square brackets. If there's more than one, separate them with a comma, like this:
[Martin-Joensson]

2024-03-07 11:20 UTC, linda-f reviewed
I like how you solved this weeks project.
You followed the design very closely and I like that you implemented the search bar. It makes the whole thing more real. I also love how many different images for all the weather types you added. This is awesome!

2024-03-07 11:20 UTC, linda-f commented on index.html
> +    <title>Weather Smeather app</title>
Love the title ;)

2024-03-07 11:20 UTC, linda-f commented on script.js
> +      temp.innerHTML = `<h1>${Math.round(data.main.temp)}°&#x1D9C;</h1>`;
Is there a reason why you decided to go with an h1 for the temperature? I am just asking because h1 is a semantic html tag and it says to the browser something like I am a title, I am important. So for SEO it is important that structure is maintained. So if you choose h1 because of the styling an size of the text I would go with a p tag and style it in CSS. I know this is nothing we learned or have to implement but I thought I let you know since I saw it.

2024-03-07 11:20 UTC, linda-f commented on script.js
> +    `${FORECAST_BASE_URL}lat=${lat}&lon=${lon}&units=metric&appid=${API_KEY}`
You made a const for this at the beginning of your code. You could use that here.

2024-03-07 11:20 UTC, linda-f commented on script.js
> +        // Only show data from the objects with an array lenght of 8. This removes the current day and any partial final day.
Nice implementation of the today problem. I didn't think of doing it that way but I love learning about different approaches.

2024-03-07 11:20 UTC, linda-f commented on script.js
> +    weather == "Mist" ||
Is there a reason why you only used two = instead of three =?
I am asking because I remember learning something that two = are more prone to errors.

2024-03-07 11:20 UTC, linda-f commented on style.css
> +  --clr_main_text: #fff;
rooting all the colors. Love that!

2024-03-08 12:27 UTC, AntonellaMorittu requested changes
Hi Martin,really well done this week! ⭐  Your code is well structured, formatted, clean and tidy. The app is working as it should - almost :) Have you tested the search functionality with different cities? Sunrise and sunset times need to be adjusted  👍 That was a stretch goal so you don't need to fix it to pass the assignment.

However, please pay attention to this basic requirement:

- the temperature should be rounded to 1 decimal

Fix these thing and you're good to go:) Keep up the awesome work 🚀

2024-03-12 13:58 UTC, HIPPIEKICK approved these changes

2024-09-17 12:46 UTC, closed without merging