weather app rainbow style
Technigo/project-weather-app pull request #91
Opened 2020-09-25 12:15 UTC by nathalienordstrom

Link to my deployed project:
https://weatherrainbow.netlify.app
My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-09-30 20:25 UTC, Snabbina reviewed
YOU DID IT NATHALIE! Its a real weather-rainbow app🌦 . Your code was easy to follow and has the necessary components to create and transform the data into a visual weather app. You have worked with responsiveness and started from mobile first! Super good! For the future watch out for to many empty spaces between code blocks and maybe having more of a habit of commenting more in your code (even in html or css if needed) , for even more readability, as the code will become more and more complex. Well done, keep hanging in there!🧘🏽‍♀️🏋🏽‍♀️

2020-09-30 20:25 UTC, Snabbina commented on Designs/Design-1/style.css
> +
some inconsistency in the spacing between your blocks of code and some curly-brackets.

2020-10-06 14:30 UTC, EmOlsz requested changes
Congratulations on your working app Nathalie! I'm very happy to see it, truly :) I hope it will get better and better with each week from now on, fingers crossed for that :)
Nonetheless, there is a lot of minor issues in your code (mostly semantical). Please, take a look on my comments and provide changes. Note that I haven't pointed out every place were you made mistake, I chose only one example of each issue.
After you will fix your code, I will approve project :)

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/.vscode/settings.json
> +}
Nope, whole hidden folder `.vscode` should be included to `.gitignore` file. Needs to be fixed.
At this point you need to do it like this :

1. On github (inside browser) delete `.vscode` from your repo.
2. On local version of project (on your hard drive) add file `.gitignore`
3. Inside that file, add separate lines `.DS_Store` and `.vscode`
4. Commit and push your changes

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/index.html
> +                <div id="sunset"></div>
You missed one closing tag somewhere here - needs to be fixed

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/index.html
> +</html>
Even should

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/index.js
> +
A lot of empty lines, let's delete them as well ;)

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/index.js
> +
Unnecessary blank line

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/index.js
> +        console.log(json)
Before pushing, we should delete all `console.log()` occurrences

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/style.css
> +
too many blank lines

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/style.css
> +#degree{
We should not style by id, classes are far better

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/style.css
> +  font
? ;)

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/style.css
> +  left: 0px;
If value is `0px`, we can omit `px` and just write `0`

2020-10-06 14:30 UTC, EmOlsz commented on Designs/Design-1/style.css
> +img {
Wrong indentation

2020-10-06 19:32 UTC, nathalienordstrom commented on Designs/Design-1/.vscode/settings.json
> +}
I don´t know the commands for that?

2020-10-13 08:58 UTC, EmOlsz approved these changes

2020-10-15 15:00 UTC, EmOlsz approved these changes

2021-02-16 17:54 UTC, closed without merging