Week 6: Weather app
Technigo/project-weather-app pull request #92
Opened 2020-09-25 12:44 UTC by monkeybusiness101

Link to my deployed project:
https://boring-feynman-5a32d5.netlify.app/

My reflections on how this week's project turned out:
It was fun to work with APIs
It was nice to work with the DOM
It was nice to work with ForEach loop. 
In general, I need to get a better understanding of conditions, loops, how to work with objects and arrays

Things I'd like to have clarified or explained in more detail:

2020-09-30 20:47 UTC, MindstormingAB requested changes
You did a great job, Max!
I liked your efficient layout, responsive by design, and the nice color combination. Your code is clean and I appreciated your informative comments that made it even easier to understand. I was impressed when I saw m location pop up in the "Choose city" field but I couldn't find in your code how you made it happen 😶 🙃
As I wrote in my comments along your code, I first thought something was wrong with my Internet connection when the "Loading.." did not disappear. You might use a more user friendly description 😉 Even if I liked the layout, I think that a little touch of padding inside your containers will not hurt.

In this project, you showed that you understood JavaScript concepts and how to use an API.

Before this project can be approved, I'd like you to make the following changes:
- resolve the issue caused by the += in the lower container
- remove console logs
- revise the indentation in the html
- split font-family and font-size in 2 lines in the css

Keep up the good work!

2020-09-30 20:47 UTC, MindstormingAB commented on code/index.html
> +            </form>
The indentation needs to be revised 🔎

2020-09-30 20:47 UTC, MindstormingAB commented on code/index.html
> +        <section id="upperContainer">Loading...</section>
Even if you will generally get clever visitors than me, you should maybe replace this "Loading..." by a more informative formulation like "Choose a city below" 😏

2020-09-30 20:47 UTC, MindstormingAB commented on code/styles.css
> +    margin-bottom: 10px;
You should avoid styling on ids. Complete your HTML elements with class names.

2020-09-30 20:47 UTC, MindstormingAB commented on code/styles.css
> +    font-family: 'Montserrat';font-size: 16px;
Nice font 😉. Split font-family and font-size on 2 different lines

2020-09-30 20:47 UTC, MindstormingAB commented on code/styles.css
> +  }
Nice!

2020-10-01 08:06 UTC, monkeybusiness101 commented
@MindstormingAB Hi Sandrine. Thank you for the valuable feedback and tips! Some things you never think about like the loading, not using id for styling and removal of console.log

This will be useful for my future development so thank you for taking time!

2020-10-01 12:56 UTC, monkeybusiness101 commented
I have now updated the code according to Sandrines feedback

2020-10-06 15:04 UTC, EmOlsz requested changes
Good job Max! Your app is working well, there are no error nor major issues. Especially I like that you used form to collect user input regarding city to display :)
Nonetheless, I see some bad habits that start to arise in your code. We should get rid of them as soon as possible. They don't have impact on how your code works, that's true, but they are considered bad practise and believe me, that's what matters for future employers (but it should matter as well for us, developers, at the end it's our code and it tells a lot about ourselves). Take a look on my comments and provide changes. After that, I'll approve your project.

Let me also address your questions :

1. **_Did I think correctly with my functions? How can I improve these?_** - Yes, you did think of them correctly. They are pretty ascetic, but this is because you have done only essentials for this project. With more requirements done, more code would come. What's important for me is that you wrapped your logic (like `fetch()` methods) into separate functions and call them when needed. Also, you use ES6 array methods like `.filter()`. I believe that if you would do your project more complex, your code would also be more complex, yet still correct.
2. **_Currently, if user does a second search, I append the new data. How can I clear this in a nice way?_** - But you are doing it in a nice way! After each `fetch()`, first thing you do is cleaning innerHTML of your container. That's proper way of doing that. Me, personally, would create HTML tags inside HTML file and later on reference to them and pass only text rather than whole HTML tags, but it's just different way of doing same thing. We introduce you to JS-in-HTML right now, so next sprint it will be easier to step in into React

2020-10-06 15:04 UTC, EmOlsz commented on code/app.js
> +        .then((result) => {
When I think about it, `.catch()` method after second `then()` would also be nice, so we can detect any server errors. Like that :

```
fetch(MY_URL)
  .then(res => res.json())
  .then(data => // do whatever you do)
  .catch(err => console.error(err));
```

Pay extra attention that I used `console.error()` instead of `console.log()`. Thanks to that our message in Console tab will have nice red background indicating that something for sure went wrong

2020-10-20 09:54 UTC, monkeybusiness101 commented on code/app.js
> +const cityForm = document.querySelector('form');
Fixed

2020-10-20 09:54 UTC, monkeybusiness101 commented on code/app.js
> +const apiKey = '1fdca83a9693b3d0d79182ed5ca69207'
Fixed

2020-10-20 09:54 UTC, monkeybusiness101 commented on code/app.js
> +const baseURL = 'https://api.openweathermap.org/data/2.5/'
Fixed

2020-10-20 09:57 UTC, monkeybusiness101 commented on code/app.js
> +cityForm.addEventListener('submit', (event) => {
Fixed

2020-10-20 09:57 UTC, monkeybusiness101 commented on code/app.js
> +    lowerContainer.innerHTML = ``
Fixed, thank you for the feedback on this!

2020-10-20 09:58 UTC, monkeybusiness101 commented on code/styles.css
> +
Fixed

2020-10-20 10:08 UTC, monkeybusiness101 commented on code/styles.css
> +.dailyForecast{
Fixed kebab-case for both ID and Class. Thank you for the feedback on this

2020-10-20 10:13 UTC, monkeybusiness101 commented on code/styles.css
> +@media only screen and (max-width: 600px) {
Fixed so that container takes 100% width up to 600 px then width is 400px

2020-10-20 10:15 UTC, monkeybusiness101 commented on code/app.js
> +                filteredForecast.forEach((day) => {
Fixed

2020-10-20 10:18 UTC, monkeybusiness101 commented on code/app.js
> +        .then((result) => {
Fixed and thank you for the feedback, good to implement in future projects.

2020-10-20 10:20 UTC, monkeybusiness101 commented
@EmOlsz Hi Maks! Thank you for the feedback. I totally lost the review and saw it now. I have reviewed your comments and made appropriate changes.

/Max

2020-10-20 19:05 UTC, EmOlsz approved these changes

2020-10-20 19:06 UTC, EmOlsz commented
> @EmOlsz Hi Maks! Thank you for the feedback. I totally lost the review and saw it now. I have reviewed your comments and made appropriate changes.
> 
> /Max

No worries Max! Thanks for changes, project is officially approved

/Maks

2021-02-16 17:53 UTC, closed without merging