Project Weather app - Karolin Albinsson
Technigo/project-weather-app pull request #93
Opened 2020-09-25 12:49 UTC by karolinalbinsson

Link to my deployed project:
https://karro-weather.netlify.app/

My reflections on how this week's project turned out:
he big problem for me was to display the local time for each location without any GMT converstions done by string methods or Date objects. I made it work after several hours of trial and error by creating a UTC-date and applied some string methods, but I'm not sure whether it is a good solution.

I also don't know what to do with potential errors thrown by the fetch. For now I log the error message but I maybe need to remove this.

Things I'd like to have clarified or explained in more detail:
How do I handle errors thrown by the fetch?

2020-09-28 17:59 UTC, Hanna-Skeppe reviewed
Overall I was really impressed by your project and the level of your coding skills in js. Good work! 🥇 
I really liked your styling of the page (minimalistic but on point) and the fact that you used position fixed on the weather today and that you had an animation on your weather-icon really made the app stand out!

Some things I thought about reviewing your code:

-On general I had a hard time to understand and follow your code. Partly because I'm not at the same skill level as you. But one suggestion to improve readability of your code would be to describe it in comments a bit more even!

-Another suggestion is to structure your CSS in order according to you HTML-structure (from top to bottom).

-Another suggestion is to maybe be consistent with the units on font-size as I see you use px and em interchangeably.

-I also wonder if it would be possible to merge a few of your functions in js?

-When you use grid, I notice that you have a lot of different classes in html/css. I wonder if there is a way to simplify this so you don't need som many classes?

It was really interesting to read your code and it really challenged me and I gained new knowledge 👍

2020-10-12 09:47 UTC, HIPPIEKICK commented on style.css
> +        grid-template-columns: 40vw 19vw 40vw;
This row creates whitespace to the right of the page

2020-10-12 09:59 UTC, HIPPIEKICK commented on index.html
> +                        </select>
I really like this idea! ⭐ Although - it was a little hard to understand that this option is there. Can you make it more visually clear somehow that it's possible to select?

2020-10-12 10:10 UTC, HIPPIEKICK commented on script.js
> +            console.log(error);
I think this is enough for now, but we will talk more about error handling in the React sprint (and the backend sprint). You could e.g. use the error message to display something valuable to the user on the page `Couldn't get weather data right now because of ${error.message}`

2020-10-12 11:40 UTC, HIPPIEKICK commented on index.html
> +            <div class="mainWeatherCell" id="weatherCellSunRise"></div>
kebab-case:
```
weather-day-2
grid-cell
empty-cell
icon-day-2
temp-day-2
main-weather-cell
```

2020-10-12 11:46 UTC, HIPPIEKICK commented on script.js
> +    let isday = false;
camelCase

2020-10-12 11:51 UTC, HIPPIEKICK requested changes
Great job Karolin! Looks really good, keep it up with the descriptive commenting as Hanna said ⭐ Some changes are needed for your code to follow the guidelines:
- Be consistent with the naming conventions. CSS classes should have kebab-case.
- Be consistent with semicolons

2020-10-13 07:34 UTC, karolinalbinsson commented
Hi, thanks for the feedback. I have made the requested changes.

2020-10-13 07:44 UTC, HIPPIEKICK approved these changes

2021-02-16 17:53 UTC, closed without merging