Weather APP - Gabriella Bolin
Technigo/project-weather-app pull request #95
Opened 2020-09-25 14:51 UTC by Gabbi-89

Link to my deployed project: https://howistheweatherapp.netlify.app/

My reflections on how this week's project turned out: Still struggling with JavaScript but learning more and more. Superfun project still and lovely to learn about API's.

Things I'd like to have clarified or explained in more detail: Struggled with some things for a very long time that I never solved, commented that in the READ ME.

2020-10-04 14:04 UTC, aagneshansson approved these changes

2020-10-04 14:04 UTC, aagneshansson commented on code/weather.js
> +                document.getElementById("weatherColor").style.border = "15px solid #bee3eb";
Great that you added different boarder color, what you could do to make the code even cleaner - you could return just the color "return #0000" and then in the function itself display it in the dom (this makes the function re-usable in future projects). 

 coloringFunction = (temp) => {
 document.body.style.borderColor = coloringFunction(todaysweather.main.temp);

2020-10-04 14:04 UTC, aagneshansson commented on code/weather.js
> +            weeks[index].querySelector('.day-descr').innerText = item.description;
Really impressive that you managed to use map even though we haven't been talking to it too much in class 👍

2020-10-04 14:04 UTC, aagneshansson commented on README.md
> +For me it was really fun starting to use API and it got very clear for me how to read the data from it. The endpoint documentation made it easier to understand this data and hopefully it will be easi
GREAT job Gabriella! This weather app is really good looking, have a lots of usable parameters and it's really usable! I think you should be proud of yourself ⭐ ⭐ also your code is really clean and easy to read! It was a pleasure to review your project ❤️

2020-10-12 14:29 UTC, EmOlsz requested changes
In general it's very nice project Gabriella, congratulations! I like how tidy your code is (there are some things to fix, but in general it's good job). You tend to think about functions and divide logic to separate chunks of code. Responsiveness is well done as well!
Take a look on my comments, there are some things I would like you to change. Please, remember that I pointed out only one occurrence of each issue, you need to go through whole project and fix other places as well. `onload` event for now is ok, no need to fix it :)

2020-10-12 14:29 UTC, EmOlsz commented on code/index.html
> +<body onload="startFunction()">
No need to add `function` postfix in name - we already know they are functions, what else could they be? :)
Moreover, instead on `onload`, you could just call your function in JS file, it's better way.
Nonetheless, I appreciate your ambition when it comes to trying different things in code

2020-10-12 14:29 UTC, EmOlsz commented on code/index.html
> +            src="./Images/placeholder.png"
Wrong indentations

2020-10-12 14:29 UTC, EmOlsz commented on code/index.html
> +            <select class="city-input" name="city" id="cityName" onchange="fetchWeather(document.getElementById('cityName').value)">
clever :)

2020-10-12 14:29 UTC, EmOlsz commented on code/style.css
> +  flex-direction: row;
Good point!

2020-10-12 14:29 UTC, EmOlsz commented on code/style.css
> +  height: 22px;
and since value is `0px`, we can omit `px` and just write `margin: 5px 5px 0 0;`

2020-10-12 14:29 UTC, EmOlsz commented on code/style.css
> +  border: 1px solid#42ade3;
That's syntax error, you forgot about whitespace - `border: 1px solid #42ade3;`

2020-10-12 14:29 UTC, EmOlsz commented on code/style.css
> +  justify-content: left;
Yep, `flex-start` would be better!

2020-10-12 14:29 UTC, EmOlsz commented on code/style.css
> +  margin: 10px 0px 25px;
`margin: 10px 0 25px;`

2020-10-12 14:29 UTC, EmOlsz commented on code/weather.js
> +    let cityName = 'Gothenburg';
No need to write `let` once again, you already declared that variable

2020-10-12 14:29 UTC, EmOlsz commented on code/weather.js
> +const startFunction = () => { // Function for loading data for Gothenburg as default when the page loads first time
As mentioned above, you could call that function directly after declaration, it would be better than with `onload` event

2020-10-12 14:29 UTC, EmOlsz commented on code/weather.js
> +        coloringFunction = () => {
This code doesn't have to be in function, you use only one time, so it's completely ok to unwrap it from function :)

2020-10-12 14:29 UTC, EmOlsz commented on code/weather.js
> +           const weeks = document.getElementsByClassName('anotherday');
wrong indentation

2020-10-12 15:42 UTC, Gabbi-89 commented on code/style.css
> +  flex-direction: row;
Thanks @aagneshansson! Now I learnt something new!

2020-10-12 15:45 UTC, Gabbi-89 commented on code/style.css
> +  justify-content: left;
Thanks! :)

2020-10-12 15:51 UTC, Gabbi-89 commented on code/index.html
> +            src="./Images/placeholder.png"
@EmOlsz Sorry I do not understand this one. How shall I do instead? In another code review you commented that class, src and alt should be on different rows if more than three.

2020-10-12 15:57 UTC, Gabbi-89 commented on code/weather.js
> +        coloringFunction = () => {
The border doesn't work if I remove the whole coloringFunction(), neither if I call the function inside.. :/

2020-10-13 09:13 UTC, EmOlsz approved these changes

2021-02-16 17:53 UTC, closed without merging